### ISSUE TITLE
RTCRtpTransceiver.setOfferedRtpHeaderExtensions

### ISSUE THREAD

**Issue by fippo** [WebKit/standards-positions#100]
## Request for position on an emerging web specification

* WebKittens who can provide input: @youennf 

### Information about the spec

* Spec Title: RTCRtpTransceiver.setOfferedRtpHeaderExtensions()
* Spec URL: https://w3c.github.io/webrtc-extensions/#dom-rtcrtptransceiver-setofferedrtpheaderextensions
* GitHub repository: https://github.com/w3c/webrtc-extensions
* Explainer (if not README.md in the repository): there is an ancient one [here](https://docs.google.com/document/d/1y1hTsMeav5ijPvoqu1R6U4YC564i1QzgkMeIqWhgiis/edit#heading=h.o92j6jwzea4x)

### Design reviews and vendor positions

* TAG Design Review: n/a
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/713

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

This is an extension to WebRTCs RTCRtpTransceiver that will enable some use-cases that are currently requiring forbidden SDP munging.

cc @alvestrand

**Comment by hober** [comment]
Barring objections, we'll mark this `position: support` in a week.

**Comment by henbos** [comment]
It's been 3 weeks, so this is "support"?

**Comment by henbos** [comment]
@hober / @youennf  can you update the label to reflect support?

**Comment by youennf** [comment]
Marking as support. @hober, should we close this thread?
