### ISSUE TITLE
Fullscreen Popup Windows

### ISSUE THREAD

**Issue by bradtriebwasser** [WebKit/standards-positions#101]
### Information about the spec

* Spec Title: Fullscreen Popup Windows
* GitHub repository: https://github.com/bradtriebwasser/fullscreen-popup
* Explainer (if not README.md in the repository):  https://github.com/bradtriebwasser/fullscreen-popup/blob/main/EXPLAINER.md

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/840
* Mozilla standards-positions issue:  https://github.com/mozilla/standards-positions/issues/714

#### Introduction
This proposal introduces the ability for web applications to open a fullscreen popup window, without the need for a separate calls to [`Window.open()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) and [`Element.requestFullscreen()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen).

The proposed enhancement would allow web applications to create a fullscreen popup window on a target display from a single user activation. The [window placement permission](https://webscreens.github.io/window-placement/#api-permissions) will be required for these capabilities.

#### Proposal
Allow sites with the `window-management` permission to open a fullscreen window on a specified display from a single user gesture. Scripts calling [window.open()](https://html.spec.whatwg.org/multipage/window-object.html#dom-open-dev) to request a popup window could also include a new fullscreen boolean window feature.

Fullscreen popup requests could also include window bounds features (e.g. left, top, width, height), with positions specified [relative to the multi-screen origin](https://w3c.github.io/window-placement/#api-window-attribute-and-method-definition-changes), to request that the window be made fullscreen on the screen containing those bounds, and also to be used as the popup window bounds after exiting fullscreen.

#### Example Code
Basic Example:
```js
window.open(url, '_blank', 'popup,fullscreen');
```

**Comment by annevk** [comment]
This depends on #117 it seems like.

Although from the example I don't understand where the target display comes in?

**Comment by bradtriebwasser** [comment]
Agree, this is dependant on #117 particularly the permission / permission policy since it gated on those.

The explainer has a more thorough example which demonstrates opening a fullscreen popup on a target display: https://github.com/bradtriebwasser/fullscreen-popup/blob/main/EXPLAINER.md#opening-a-fullscreen-popup-on-another-display

It's worth noting this proposal is independent of the ability to open popups on target displays, but the example is shown to show the capabilities of the feature in conjunction with #117's ability to open popups on any display.

**Comment by michaelwasserman** [comment]
Chromium is no longer pursuing this feature directly; see the superseding Standards Position request in Issue #345.
