### ISSUE TITLE
RTCRtpEncodingParameters.scalabilityMode

### ISSUE THREAD

**Issue by Orphis** [WebKit/standards-positions#103]
## Request for position on an emerging web specification

* WebKittens who can provide input: @youennf 

### Information about the spec

* Spec Title: WebRTC-SVC
* Spec URL: https://www.w3.org/TR/webrtc-svc/
* GitHub repository: https://github.com/w3c/webrtc-svc/
* Explainer: Adding SVC (Scalable Video Coding) related control APIs to WebRTC.

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/396
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/544

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

The goal would be to get feedback on adding `scalabilityMode` to [RTCRtpEncodingParameters](https://www.w3.org/TR/webrtc/#dom-rtcrtpencodingparameters). I understand that additions to [RTCRtpCodecCapability](https://www.w3.org/TR/webrtc/#dom-rtcrtpcodeccapability) are probably not necessary to launch the API as similar functionality can be achieved with the `MediaCapabilities` API.

**Comment by youennf** [comment]
Addition seems good.
Discussed offline with @Orphis and the discovery of the values is happening in MediaCapabilities, which seems consistent.

**Comment by youennf** [comment]
One thing to look at is that the actual values implemented for VP8, VP9 and so on are open-ended but are really important for interop. Maybe there should be guidelines somewhere to get consistent support.

**Comment by hober** [comment]
Given @youennf's comments above, I'll mark this as `position: support` a week from now unless anyone objects.
