### ISSUE TITLE
Request for Position: FileSystemHandle Remove Self

### ISSUE THREAD

**Issue by a-sully** [WebKit/standards-positions#104]
## Request for position on an emerging web specification

* WebKittens who can provide input: @annevk, @szewai

### Information about the spec

* Spec URL: whatwg/fs#9
* GitHub repository: [whatwg/fs](https://github.com/whatwg/fs/)
* Explainer: https://github.com/a-sully/fs/pull/1

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/773
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/716

### Anything else we need to know

The explainer focuses mainly on the use cases outside of the Origin Private File System, but within the OPFS this method is (just) [a significant improvement in API ergonomics](https://github.com/a-sully/fs/blob/6abfb840112d137c22fbf0fb986471dfe63a89fc/Remove.md#improve-ergonomics-of-the-api).

**Comment by a-sully** [comment]
Good point - [the WPTs assert that you can't remove a root](https://github.com/web-platform-tests/wpt/blob/2f2fa4f92e81df6e159ccf7b1ad2eae441303934/file-system-access/script-tests/FileSystemBaseHandle-remove.js#L98), but it's not currently in the spec language. I can fix that

**Comment by a-sully** [comment]
Oh just kidding, this is already covered. Conversation is happening here https://github.com/whatwg/fs/pull/9/files#r1042179453

**Comment by hober** [comment]
Closing as we've identified our position.
