### ISSUE TITLE
CSS Grid Masonry Layout

### ISSUE THREAD

**Issue by bennypowers** [WebKit/standards-positions#105]
### Information about the spec

* Spec Title: CSS Grid Layout Module Level 3
* Spec URL: https://drafts.csswg.org/css-grid-3/

### Design reviews and vendor positions

* Mozilla standards-positions issue: (implemented)

### Anything else we need to know

Masonry layout is a layout method where one axis uses a typical strict grid layout, most often columns, and the other a masonry layout. On the masonry axis, rather than sticking to a strict grid with gaps being left after shorter items, the items in the following row rise up to completely fill the gaps. - [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Masonry_Layout)

**Comment by dgrammatiko** [comment]
https://github.com/WebKit/WebKit/pull/6940

**Comment by hober** [comment]
Talked about this with several colleagues today and we're generally supportive. We'll add the `position: support` label in a week unless anybody objects.
