### ISSUE TITLE
Resource Timing: Add interim response timings

### ISSUE THREAD

**Issue by noamr** [WebKit/standards-positions#109]
## Request for position on an emerging web specification

**(Please delete inapplicable rows.)**

* WebKittens who can provide input: 

### Information about the spec

* Spec Title: Resource Timing: Add interim response timings
* Spec URL: https://github.com/w3c/resource-timing/pull/366 and https://github.com/whatwg/fetch/pull/1483
* GitHub repository: https://github.com/w3c/resource-timing/

### Design reviews and vendor positions

* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/722

### Anything else we need to know

Requested by Shopify and other users of resource timing APIs, to add more information about a response:
- when the final response arrives (not just the interim 103 response)
- When the headers are complete
- When the body stream starts

All of these would be protected by `Timing-Allow-Origin`. See attached spec PRs.

**Comment by annevk** [comment]
cc @achristensen07

**Comment by annevk** [comment]
Colleagues and I discussed this and are okay with exposing these three additional timings with the usual constraints. As discussed we would like it to reflect the first interim response and not the first interim response that happens to be a 103.

As such I suggest we mark this as "position: support" one week from now.
