### ISSUE TITLE
Web Share Target API

### ISSUE THREAD

**Issue by matteocargnelutti** [WebKit/standards-positions#11]
## Request for position on an emerging web specification

* WebKittens who can provide input: @hortont424, @marcoscaceres 

### Information about the spec

* Spec Title: Web Share Target API
* Spec URL: https://w3c.github.io/web-share-target/  _(Unofficial Draft)_
* GitHub repository: https://github.com/w3c/web-share-target

### Design reviews and vendor positions

* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/176

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=194593

### Anything else we need to know

**Summary:** While the [Web Share API](https://www.w3.org/TR/web-share/) allows browsers to make use of the operating system's native _"share"_ mechanism in web-to-native contexts, the [Web Share Target API](https://github.com/w3c/web-share-target) intent is to enable web-to-web and native-to-web sharing scenarios. 
What is WebKit's position on this spec?

**Comment by othermaciej** [comment]
Is this an Unofficial Draft of the Web Apps WG? Is it a community group thing? Can't tell the venue from the document itself.

**Comment by matteocargnelutti** [comment]
@othermaciej My understanding is that this draft comes from the WICG, as the [Specification - Level 2 doc](https://w3c.github.io/web-share-target/level-2/) suggests:

> [...] Web Share Target API - Level 2 Specification, published by the Web Incubator Community Group under the W3C Community Contributor License Agreement (CLA). [...]

https://github.com/WICG/web-share-target/ redirects to https://github.com/w3c/web-share-target.

**Comment by marcoscaceres** [comment]
It's an unofficial spec, but it's in scope for WebApps WG should another implementer become interested:
https://www.w3.org/2019/05/webapps-charter.html#wicgspecs

**Comment by othermaciej** [comment]
OK, so for now WICG, but has fast track to go to Web Apps WG depending on interest?

**Comment by marcoscaceres** [comment]
That's correct, yes.

**Comment by hober** [comment]
@hortont424, thoughts?

**Comment by othermaciej** [comment]
Potential security concerns if this allows a website to appear in the Share Sheet with a site-chosen icon and name, as it can then intentionally duplicate a popular or preinstalled app and thus mislead users.

**Comment by tomayac** [comment]
The user would need to add the app to their home screen pro-actively, so when they are on **Banana Game** with a **[🍌]** icon and they try to add it and it suddenly says **Facebook Messenger** with a **[💬]**, they would notice there.

**Comment by othermaciej** [comment]
So this API is only usable by installed/homescreen web apps? Not in the browser?

**Comment by othermaciej** [comment]
So this API is only usable by installed/homescreen web apps? Not in the browser?

**Comment by mtom55** [comment]
> So this API is only usable by installed/homescreen web apps? Not in the browser?

It’s up to the user agent, but

**Comment by matteocargnelutti** [comment]
> @othermaciej: So this API is only usable by installed/homescreen web apps? Not in the browser?

In its current state, [the spec leaves the user agent determine how, if, and when targets should be registered](https://w3c.github.io/web-share-target/#registration-of-web-share-targets).  

[The spec suggests different strategies that can be used to determine if the share target(s) should be registered](https://w3c.github.io/web-share-target/#registration-of-web-share-targets:~:text=Examples%20of%20registration%20strategies%20that%20user%20agents%20can%20employ%20are%3A): whether or not the web app is installed is one of them. 

[Chrome's current implementation of the Web Share Target API](https://web.dev/web-share-target/) requires the web app to be installed.

---

> @othermaciej: Potential security concerns if this allows a website to appear in the Share Sheet with a site-chosen icon and name, as it can then intentionally duplicate a popular or preinstalled app and thus mislead users.

[The spec also lists spoofing as a risk of _"particular concern"_](https://w3c.github.io/web-share-target/#security-and-privacy-considerations), and suggests that this risk is heightened when the user agent doesn't require the web app to be installed.

**Comment by tomayac** [comment]
@othermaciej I have opened https://github.com/w3c/web-share-target/issues/109 asking if some sort of installation ceremony should be made obligatory by the spec. In practice, the API in its current implementation in Chromium already requires apps to be installed for it to have an effect.

**Comment by othermaciej** [comment]
> 
> > @othermaciej: Potential security concerns if this allows a website to appear in the Share Sheet with a site-chosen icon and name, as it can then intentionally duplicate a popular or preinstalled app and thus mislead users.
> 
> [The spec also lists spoofing as a risk of _"particular concern"_](https://w3c.github.io/web-share-target/#security-and-privacy-considerations), and suggests that this risk is heightened when the user agent doesn't require the web app to be installed.

Ideally there should be not just an identification of the risk but also something in the spec (even if just a suggestion) to mitigate it. The risk is also heightened if it's possible for a web app's name or icon to change post-install (without user confirmation).

**Comment by tomayac** [comment]
Regarding changing icons and/or name: both are considered security-sensitive and the spec [mandates](https://w3c.github.io/manifest/#updating) UAs make users aware of such changes.

**Comment by marcoscaceres** [comment]
**This is a DRAFT POSITION and does not represent the consensus of the WebKit community.** 

However, unless anyone objects by Friday 16th of November 2022, we will make the below the "official position". Please feel free to object or requests more time if needed. Please expressed support through the thumbs up reaction or additional comments (no +1 comments please!).

> WebKit’s position is "neutral" but with concerns.  
>
> The main pro of the API is that it allows applications applications that have been added to the home screen to participate as share targets, putting them on a more equal footing with other applications participating as share targets. We continue to evaluate ways to determine user trust for arbitrary websites (those not “installed”) to serve as a share targets. Stronger spec wording may be required to make sure that a regular web application can’t change its visual identity after the user has registered a site as a share target (e.g., perhaps it might be prudent to just say that an application MUST be “installed” per Web Manifest).
> 
> The WebKit community probably needs to evaluate if the mechanism proposed is compatible across various platforms (particularly macOS, which use “Share Extensions”, and iOS, which relies on “Actions“). Further investigation is needed to evaluate how this would integrate in other platforms, like Linux.  
> 
> Other positive is how it integrates with existing web content by leveraging HTTP `GET` and `POST` in the form of a `Request`. However, the WebKit community would need to further evaluate how well it integrates with both navigating and the use of the Fetch API: presumedly, the origin of the request is set when it is created to be in the correct context, etc. plus probably need to verify the behavior with respect to HTML’s navigation algorithm. 
> 
> As a side, it would be good to see the spec [migrate away from using Web IDL](https://github.com/w3c/web-share-target/pull/106) for the extensions to Web Manifest.

**Comment by marcoscaceres** [comment]
Personally, I still think we need to think about this more in the Web Community at large. I'm personally worried about creating an "installed web" and a regular web: where some things only work if an app is installed. We should avoid that as much as possible, though it may be unavoidable in this case.

Having said that, "neutral" shouldn't be seen as negative. Maybe with a bit of work, Web Apps WG can turn it into something worth "support"ing?

**Comment by hober** [comment]
Closing as we've identified our position.
