### ISSUE TITLE
CSS root font units

### ISSUE THREAD

**Issue by danielsakhapov** [WebKit/standards-positions#112]
### Information about the spec

* Spec Title: CSS Values and Units Module
* Spec URL: https://drafts.csswg.org/css-values/#font-relative-lengths
* GitHub repository: https://github.com/w3c/csswg-drafts

### Design reviews and vendor positions

* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/725

### Anything else we need to know

Request specifically for rex, rch, ric, rcap.

**Comment by annevk** [comment]
cc @anttijk @jensimmons

**Comment by nt1m** [comment]
Generally this seems like an useful feature, though I think this requires unconditionally initializing font metrics for the root element as opposed to `rem` or `rlh` which just read from the computed style. Not sure if that is an issue or not. cc @litherum who may have an informed opinion on this.

**Comment by litherum** [comment]
We are positive on these new units. They seem useful and easy to implement. We don’t expect performance problems with them.

**Comment by annevk** [comment]
Marking as "position: support" per above comments. (Not waiting another week as plenty of time passed since Tim's initial comment.)
