### ISSUE TITLE
Request for position: Autoplay Policy Detection

### ISSUE THREAD

**Issue by alastor0325** [WebKit/standards-positions#113]
### Information about the spec

* Spec Title: Autoplay Policy Detection
* Spec URL: https://w3c.github.io/autoplay/
* GitHub repository: https://github.com/w3c/autoplay/
* Issue Tracker (if not the repository's issue tracker): https://github.com/w3c/autoplay/issues/
* Explainer (if not README.md in the repository): https://github.com/w3c/autoplay#readme

### Design reviews and vendor positions

* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/675

### Bugs tracking this feature

* Mozilla Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1773551

### Anything else we need to know

This spec aims to provide information to web authors in order to let them know if autoplay is allowed or not.

**Comment by annevk** [comment]
Colleagues and I are supportive of this. I suggest we label it as "position: support" 7 days from now.

**Comment by hober** [comment]
Closing as we've identified our position.
