### ISSUE TITLE
requestPostAnimationFrame

### ISSUE THREAD

**Issue by smfr** [WebKit/standards-positions#116]
## Request for position on an emerging web specification

* WebKittens who can provide input: 

@rniwa @cdumez 

### Information about the spec

* Spec Title: requestPostAnimationFrame
* Spec URL: https://github.com/WICG/request-post-animation-frame/blob/main/explainer.md
* Explainer (if not README.md in the repository): 

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: 

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=249798
* Radar: 

### Anything else we need to know

Brief summary of the issue or the subject of the spec.

Adds a hook to get started on rendering the next frame as soon as possible, when layout is known to be clean.

**Comment by annevk** [comment]
Given https://github.com/WICG/request-post-animation-frame/issues/5 by @marcoscaceres I think this proposal might no longer be active.

**Comment by marcoscaceres** [comment]
Yeah, looks like it’s long dead. @smfr, ok if we close this or is this something we might want to revive?

**Comment by smfr** [comment]
Closing.
