### ISSUE TITLE
Programatically disabling hardware encoding/decoding in WebRTC

### ISSUE THREAD

**Issue by fippo** [WebKit/standards-positions#119]
## Request for position on an emerging web specification

* WebKittens who can provide input: @youennf 

### Information about the specification

* Title: (part of webrtc-extensions)
* URL: https://w3c.github.io/webrtc-extensions/#disable-hardware
* GitHub repository: https://github.com/w3c/webrtc-extensions

### Design reviews and vendor positions

* TAG Design Review: (to be determined if this is necessary)
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/728

### Bugs tracking this feature

* WebKit Bugzilla:
* Radar:

### Anything else we need to know

The hardware encoders used by Safari are problematic as well as seen from these issues from the list-of-doom:
iPadOS 15 / iOS 15 unable to decode VP9 stream
https://bugs.webkit.org/show_bug.cgi?id=230604#c11

Safari: VP9-SVS no video stream from remote peer on some devices
https://bugs.webkit.org/show_bug.cgi?id=231074

Apple Silicon: Black screen share on remote side of peerconnection
https://bugs.webkit.org/show_bug.cgi?id=236870

and last but not least the infamous https://bugs.webkit.org/show_bug.cgi?id=232006

**Comment by annevk** [comment]
cc @youennf

**Comment by nils-ohlmeier** [comment]
> Also, the potential fingerprinting issues are not really mentioned. And the proposal is not aligned with Media Capabilities or WebCodecs.

Just as word of caution: Media Capabilities increases the fingerprinting as well. Especially since the playback API's are not guarded with anything as far as I know.

But I do agree that it would make more sense to continue extending the Media Capabilities API for encoding purposes, especially if it this could get leveraged in WebRTC and WebCodecs.

**Comment by youennf** [comment]
Until the proposal is reworked to better align with existing APIs, I would go with `position: oppose` given the potential perf and fingerprinting issues.

**Comment by hober** [comment]
Barring objections, we'll mark this `position: oppose` in a week.
