### ISSUE TITLE
Declarative Shadow DOM

### ISSUE THREAD

**Issue by bennypowers** [WebKit/standards-positions#12]
## Request for position on an emerging web specification

* WebKittens who can provide input: @rniwa

### Information about the spec

* Spec Title: Declarative Shadow DOM
* Spec URL: https://github.com/whatwg/dom/issues/831
* GitHub repository: WHATWG
* Issue Tracker (if not the repository's issue tracker): https://github.com/whatwg/dom/issues/831
* Explainer (if not README.md in the repository): https://github.com/mfreed7/declarative-shadow-dom/blob/master/README.md

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/494
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/335

### Bugs tracking this feature

* WebKit Bugzilla: [Prototype declarative shadow DOM](https://bugs.webkit.org/show_bug.cgi?id=245556)
* Radar: _

### Anything else we need to know

Would unblock shadow DOM use in above-the-fold content in performance sensitive pages and applications.

**Comment by rniwa** [comment]
One open issue I have with this feature is the compatibility with scoped custom element registry. I'd like to figure out how these two features fit together before shipping either.

**Comment by thescientist13** [comment]
@rniwa 
Opened up an issue for tracking https://github.com/WebKit/standards-positions/issues/38

**Comment by rniwa** [comment]
We're prototyping this in https://bugs.webkit.org/show_bug.cgi?id=245556

**Comment by annevk** [comment]
Given that we're actively prototyping and helping out with standardization I would suggest we add the "position: support" label one week from today.

**Comment by hober** [comment]
Closing as we've identified our position.
