### ISSUE TITLE
FedCM Multi IDP support

### ISSUE THREAD

**Issue by npm1** [WebKit/standards-positions#120]
## Request for position on an emerging web specification

* WebKittens who can provide input: @johnwilander maybe (Apple has not been very involved in the FedID CG).

### Information about the specification

* Title: FedCM with multiple IDP support
* URL: 
* GitHub repository: https://github.com/fedidcg/FedCM
* Explainer (if not README.md in the repository): https://github.com/fedidcg/FedCM/blob/main/proposals/multi-idp-api.md

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/803
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/730

### Anything else we need to know

Hey, I am requesting standards position on the FedCM API multi IDP support. The explainer is up from GitHub and is based on a bunch of discussions in the FedID CG. The initial FedCM API had positive signal, but filing a separate issue for this substantial addition.

**Comment by marcoscaceres** [comment]
Closing in favor or https://github.com/WebKit/standards-positions/issues/309 as we have never given a position of the actual FedCM spec.
