### ISSUE TITLE
FileSystemFileHandle.move() for local files

### ISSUE THREAD

**Issue by a-sully** [WebKit/standards-positions#121]
## Request for position on an emerging web specification

* WebKittens who can provide input: @annevk, @szewai 

### Information about the specification

* URL: https://github.com/whatwg/fs/pull/10 (though that currently specifies directory moves, too)
* GitHub repository: https://github.com/whatwg/fs/ and https://github.com/WICG/file-system-access
* Explainer: https://github.com/a-sully/fs/pull/2

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/805
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/732

### Anything else we need to know

This is specifically asking for input for moving/renaming ___local___ (i.e. not in the Origin Private File System - which is already shipped) ___files___ (not directories - which is different enough that it will have a separate explainer)

**Comment by annevk** [comment]
As per #28 this is not a capability that colleagues and I think should be part of the web platform.

**Comment by hober** [comment]
Given @annevk's comment I'll mark this as `position: oppose` in 7 days unless anybody objects.
