### ISSUE TITLE
Request for position: new dialog initial focus algorithm

### ISSUE THREAD

**Issue by josepharhar** [WebKit/standards-positions#123]
## Request for position on an emerging web specification

* WebKittens who can provide input:
  * @annevk 
  * @nt1m 

### Information about the specification

* Title: New dialog initial focus algorithm
* URL: https://github.com/whatwg/html/pull/8199
* GitHub repository: https://github.com/whatwg/html
* Issue Tracker (if not the repository's issue tracker):
* Explainer (if not README.md in the repository): https://github.com/whatwg/html/wiki/dialog--initial-focus,-a-proposal

### Design reviews and vendor positions

* TAG Design Review: none
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/734

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=250795
* Radar:

**Comment by annevk** [comment]
@nt1m I think from the comment on the PR you were good here either way, right? If so we should just resolve this as "position: support" 7 days from now, unless anyone else has strong feelings about this but I kinda doubt it.

**Comment by hober** [comment]
Closing as we've identified our position.
