### ISSUE TITLE
Request for Position: Mixed Content - Upgrading of "passive" mixed content

### ISSUE THREAD

**Issue by mozfreddyb** [WebKit/standards-positions#124]
## Request for position on an emerging web specification

* WebKittens who can provide input: Not sure. @annevk or @johnwilander as a first step and then probably some more?

### Information about the specification

* Title: Mixed Content
* URL: https://w3c.github.io/webappsec-mixed-content/
* GitHub repository: https://github.com/w3c/webappsec-mixed-content/
* Issue Tracker (if not the repository's issue tracker):

* Explainer (if not README.md in the repository):

There is no explainer. Here are some within the latest Editor's Draft (formerly called "Level 2").
1. upgrading passive mixed content (audio, video, img elements) on HTTPS pages without a fallback
2. deprecation of CSP `block-all-mixed-content`
3. warnings for insecure downloads (OK to leave out in this standards position for now)

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/420
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/668

### Bugs tracking this feature

* WebKit Bugzilla:
* Radar:

**Comment by annevk** [comment]
Colleagues and I chatted about 1 and 2 and agree those are good changes. 3 is probably best left to the discretion of UI engineers, but some kind of encouragement seems reasonable.

As such I suggest we label this "position: support" 7 days from now.

**Comment by hober** [comment]
Closing as we've identified our position.
