### ISSUE TITLE
MathML colspan attribute for the `<mtd>` element

### ISSUE THREAD

**Issue by fred-wang** [WebKit/standards-positions#126]
## Request for position on an emerging web specification

* WebKittens who can provide input: @annevk 

### Information about the specification

* Title: MathML Core (mtd@colspan)
* URL: https://w3c.github.io/mathml-core/#entry-in-table-or-matrix-mtd

### Design reviews and vendor positions

* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/743

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=251489

### Anything else we need to know

MathML 3 has an attribute called `columspan` [1] that is implemented in WebKit relying on the implementation of HTML's `colspan` attribute [2].

MathML Core instead switches to `colspan` for consistency with HTML [3] and clarifies things like parsing. In particular this makes things confusing for users who are familiar with HTML.

Would WebKit be interested in supporting this name (together with the legacy name `columnspan`)?

[1] https://www.w3.org/TR/MathML3/chapter3.html#presm.mtdatts
[2] https://searchfox.org/wubkat/search?q=columnspan&path=&case=true&regexp=false
[3] https://w3c.github.io/mathml-core/#entry-in-table-or-matrix-mtd

**Comment by annevk** [comment]
> In particular this makes things confusing for users who are familiar with HTML.

Less confusing presumably?

Can the parser be shared or will both attributes need their own parser?

I saw in the Mozilla issue that the plan is to get rid of the old attribute. That seems somewhat concerning. Generally features we add should be supported indefinitely. If we keep tweaking small things and breaking websites web developers will lose trust.

**Comment by annevk** [comment]
Has this proposal been abandoned?

**Comment by fred-wang** [comment]
Yes.
