### ISSUE TITLE
Import Attributes (was: Import Assertions)

### ISSUE THREAD

**Issue by annevk** [WebKit/standards-positions#128]
### Information about the specification

* Title: Import Attributes
* URL: https://tc39.es/proposal-import-attributes/
* GitHub repository: https://github.com/tc39/proposal-import-attributes

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/535
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/373

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=243622

Also https://bugs.webkit.org/show_bug.cgi?id=251600.

### Anything else we need to know

There's a somewhat late outstanding host-integration issue: https://github.com/whatwg/html/issues/7233#issuecomment-1407049226.

**Comment by annevk** [comment]
@Constellation, others, and I discussed this and are supportive provided the host-integration issue is resolved. As the primary concern with host integration is the name, adding the relevant concerns label as well.

**Comment by Constellation** [comment]
Right now, we have implementation for the currently-proposed (and will be changed) import-assertions, and disabling it behind a runtime flag due to stage-2 downgrade. Once the integration is solved, we should update and enable it.
