### ISSUE TITLE
Request for position: linear() easing function

### ISSUE THREAD

**Issue by danielsakhapov** [WebKit/standards-positions#130]
### Information about the specification

* Title: Request for linear() easing function
* URL: https://w3c.github.io/csswg-drafts/css-easing/#the-linear-easing-function
* GitHub repository: https://github.com/w3c/csswg-drafts
* Issue Tracker (if not the repository's issue tracker): https://bugs.webkit.org/show_bug.cgi?id=240061

### Design reviews and vendor positions

* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/747

### Anything else we need to know

Looks useful and not hard to implement.

**Comment by annevk** [comment]
cc @grorg

**Comment by jakearchibald** [comment]
Fwiw, there's been a good amount of interest for using this to implement bounce, elastic, and [emphasised easing](https://m3.material.io/styles/motion/easing-and-duration/tokens-specs#cbea5c6e-7b0d-47a0-98c3-767080a38d95) effects.
