### ISSUE TITLE
FedCM: auto re-authentication support

### ISSUE THREAD

**Issue by yi-gu** [WebKit/standards-positions#131]
## Request for position on an emerging web specification

* WebKittens who can provide input: perhaps @pascoej who has been attending FedIDCG meetings 

### Information about the specification

* Title: FedCM: Auto re-authentication
* URL: 
* GitHub repository: https://github.com/fedidcg/FedCM
* Explainer (if not README.md in the repository): https://github.com/fedidcg/FedCM/issues/429

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/813

Mozilla agreed on the feature itself but need more work to align on the API shape: https://github.com/fedidcg/FedCM/issues/429#issuecomment-1426162273

### Anything else we need to know

The initial FedCM API had positive signal from WebKit. This is an additional feature for users who have created a federated account in the past (conceptually the same as `mediation: silent` in CredentialManagement API).

**Comment by marcoscaceres** [comment]
Closing in favor or https://github.com/WebKit/standards-positions/issues/309 as we have never given a position of the actual FedCM spec.

**Comment by marcoscaceres** [comment]
Closing in favor or https://github.com/WebKit/standards-positions/issues/309 as we have never given a position of the actual FedCM spec.
