### ISSUE TITLE
Request for position: Use `v` flag instead of `u` for HTML `pattern` attribute RegExps

### ISSUE THREAD

**Issue by mathiasbynens** [WebKit/standards-positions#132]
## Request for position on an emerging web specification

* WebKittens who can provide input: @msaboff, @annevk

### Information about the specification

* Title: Use `v` flag instead of `u` for HTML `pattern` attribute RegExps
* URL: https://github.com/whatwg/html/pull/7908
* GitHub repository: https://github.com/whatwg/html/pull/7908
* Issue Tracker (if not the repository's issue tracker): https://github.com/whatwg/html/pull/7908
* Explainer (if not README.md in the repository): https://github.com/whatwg/html/pull/7908

### Design reviews and vendor positions

* TAG Design Review: N/A
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/745

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=pattern-v
* Radar: rdar://problem/105268069

### Anything else we need to know

The proposed change to the HTML `pattern` attribute swaps the `u` RegExp flag for [the new `v` flag](https://github.com/tc39/proposal-regexp-v-flag), enabling the use of three new features:

- set notation
- string literal syntax
- Unicode properties of strings

The spec patch at [https://github.com/whatwg/html/pull/7908](https://github.com/whatwg/html/pull/7908) lists the potentially breaking changes. Some patterns that previously would compile, now throw an early error with the `v` flag — specifically those with a character class including either an unescaped special character or a double punctuator.

**We expect such patterns to be rare.** To validate those assumptions we’ve added two use counters to Chromium: `V8RegExpUnicodeSetIncompatibilitiesWithUnicodeMode` tracks patterns in any JavaScript `u` RegExps (not just those implicitly generated via the `pattern` attribute) that would throw if they were used with the `v` flag, and `HTMLPatternRegExpUnicodeSetIncompatibilitiesWithUnicodeMode` does the same thing for the smaller & more relevant set of RegExps that are compiled via the HTML `pattern` attribute.

Importantly, note that throwing patterns result in `inputElement.validity.valid === true` for any input value (as if the `pattern` attribute wasn’t present), so the only compatibility risk is that some value/pattern combinations that would previously result in `inputElement.validity.valid === false` now result in `inputElement.validity.valid === true`. So even if the UseCounters are non-zero, it could be that there is no actual breakage.

**Comment by hober** [comment]
Closing as we've identified our position.
