### ISSUE TITLE
scrollbar-color CSS property

### ISSUE THREAD

**Issue by lukewarlow** [WebKit/standards-positions#134]
## Request for position on an emerging web specification

**(Please delete inapplicable rows.)**

* WebKittens who can provide input:

### Information about the specification

* Title: CSS Scrollbars Styling Level 1
* URL: https://www.w3.org/TR/css-scrollbars-1/#scrollbar-color
* GitHub repository: https://github.com/w3c/csswg-drafts/tree/main/css-scrollbars-1

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/563

Mozilla are the only ones who have implemented this property so far. (Chromium might have a WIP implementation)

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=231590
* Radar: rdar://84418022

### Anything else we need to know

Currently to style scrollbars in WebKit you need to use the legacy `::-webkit-scrollbar` pseudo styling. This property would allow  styling scrollbar colors through a standard property.

**Comment by hober** [comment]
@smfr, thoughts?

**Comment by lukewarlow** [comment]
This is what Firefox's implementation results in on macOS with always on scrollbars.

![image](https://github.com/WebKit/standards-positions/assets/32498324/15fc6901-2be8-42a4-8b3a-a0fd40ff8957)

From a quick test editing the hardcoded value in Chrome it looks to be possible to customise them too (thought this property isn't supported in Chrome atm)

![image](https://github.com/WebKit/standards-positions/assets/32498324/46245ae0-1468-4c41-94b2-3759687ad490)

However, WebKit's scrollbar implementation seems to defer to some Apple internal SDK so I don't think this property would be as easily implemented in Safari. Potentially WebKit would have to go down the custom scrollbar path for this property?
