### ISSUE TITLE
scrollbar-gutter CSS Property

### ISSUE THREAD

**Issue by lukewarlow** [WebKit/standards-positions#135]
## Request for position on an emerging web specification

**(Please delete inapplicable rows.)**

* WebKittens who can provide input:

### Information about the specification

* Title: CSS Overflow Level 3
* URL: https://drafts.csswg.org/css-overflow-3/#scrollbar-gutter
* GitHub repository: https://github.com/w3c/csswg-drafts/tree/main/css-overflow-3

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/520
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/488

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=167335
* Radar: rdar://problem/30153666

### Anything else we need to know

This property is useful for preventing layout shift due to scrollbars.

**Comment by hober** [comment]
@smfr, thoughts?

**Comment by smfr** [comment]
The property as specified now has no effect when scrollbars are overlay scrollbars; it's primarily about avoiding layout changes when `overflow:auto` gains or loses a scrollbar, which seems OK.

**Comment by yisibl** [comment]
I think that needs to be addressed first: 
https://github.com/w3c/csswg-drafts/issues/4674#issuecomment-1867413830
