### ISSUE TITLE
Display and content-visibility animations

### ISSUE THREAD

**Issue by josepharhar** [WebKit/standards-positions#147]
### Information about the specification

* Title: Display and content-visibility animations
* URL: https://github.com/w3c/csswg-drafts/issues/6429
* Explainer (if not README.md in the repository): https://github.com/w3c/csswg-drafts/issues/6429#issuecomment-1318933547

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/824
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/762

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

Support specifying display and content-visibility in animations. This support allows for developers to create exit animations after which the element automatically becomes display: none or content-visibility: hidden without needing to write any javascript to handle that switch after the animation is finished. This allows exit animations for elements to be added purely in CSS.

**Comment by gsnedders** [comment]
cc @graouts

**Comment by nt1m** [comment]
I'll mark this as positive in a week pending objections, because we think this feature is useful and given:
* https://github.com/WebKit/WebKit/pull/22116
* https://github.com/WebKit/WebKit/pull/22902
* https://github.com/WebKit/WebKit/pull/22974
