### ISSUE TITLE
CSS transition-behavior property

### ISSUE THREAD

**Issue by josepharhar** [WebKit/standards-positions#148]
### Information about the specification

* Title: CSS transition-behavior property
* URL: https://drafts.csswg.org/css-transitions-2/#transition-behavior-property
* Explainer (if not README.md in the repository): none

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/825
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/763

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

The transition-behavior property enables transitions for discrete properties when the `allow-discrete` value is used. Discrete properties will transition from their initial to final value at 50% through the transition, unless one of the values is display:none or content-visibility:hidden, in which case the not-invisible value will be used for the entire duration of the transition.

CSSWG issue: https://github.com/w3c/csswg-drafts/issues/8857

**Comment by gsnedders** [comment]
cc @graouts

**Comment by nt1m** [comment]
I will mark this as `position: support` one week from now pending objections, given we have implemented this in WebKit:
* https://github.com/WebKit/WebKit/commit/a0f7f0bc002c88904ebd534d3daa2d12d92c1545
* https://github.com/WebKit/WebKit/commit/336b9f90b63d33c8b54eb526fd7cd0f67a892aba
