### ISSUE TITLE
scrollend event

### ISSUE THREAD

**Issue by DavMila** [WebKit/standards-positions#150]
### Information about the specification

* Title: Scrollend Events
* URL: https://drafts.csswg.org/cssom-view/#scrolling-events

* Explainer (if not README.md in the repository): https://github.com/argyleink/scrollend-explainer/blob/main/README.md

### Design reviews and vendor positions

Already shipped in Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1803435.

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=201556
* Radar: rdar://69443508

### Anything else we need to know

The “scrollend” event aims to give developers a reliable way to tell that a scroll has completed. This way, developers don’t have to write ad-hoc javascript to try to figure out when a scroll has completed.

**Comment by gsnedders** [comment]
this is https://bugs.webkit.org/show_bug.cgi?id=201556 / rdar://problem/69443508

**Comment by markcellus** [comment]
I opened https://github.com/argyleink/scrollend-explainer/issues/1 btw

**Comment by o-t-w** [comment]
Maybe you could also give a position on [overscroll](https://wicg.github.io/overscroll-scrollend-events/#the-overscroll-and-scrollend-events), which imo would be a very useful feature

**Comment by annevk** [comment]
I discussed this with colleagues and we suggest "position: support" for this as it'll give web developers a better signal. If anyone disagrees please speak up within a week!
