### ISSUE TITLE
Scroll-driven animations

### ISSUE THREAD

**Issue by flackr** [WebKit/standards-positions#152]
### Information about the specification

* Title: Scroll-driven animations
* URL: https://drafts.csswg.org/scroll-animations-1/
* GitHub repository: https://github.com/w3c/csswg-drafts/tree/main/scroll-animations-1

### Design reviews and vendor positions

* TAG Design Review: Previous review at https://github.com/w3ctag/design-reviews/issues/521

(might need re-review)

* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/347

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=222295
* Radar:

### Anything else we need to know

There was a [previous request for position in 2020 on the webkit-dev mailing list](https://lists.webkit.org/pipermail/webkit-dev/2020-June/031228.html) to which support was expressed. The spec has since undergone a [fairly radical shift towards better css support](https://github.com/w3c/csswg-drafts/issues/6674) with working group resolutions for all of the major decision points. We are down to a very small set of issues remaining being tracked by https://github.com/w3c/csswg-drafts/projects/33. I just wanted to confirm the position now that we have the new API design.

**Comment by bramus** [comment]
/ping @smfr, as we just chatted about it.

**Comment by annevk** [comment]
@smfr it seems like this is not particularly controversial, but for next time please follow https://github.com/WebKit/standards-positions#resolving-an-issue-with-a-position to give others in the WebKit community some time to chime in before the issue appears more "final".
