### ISSUE TITLE
overflow:overlay aliases overflow:auto

### ISSUE THREAD

**Issue by chrishtr** [WebKit/standards-positions#157]
### Information about the specification

* Title: [css-overflow-3] Make `overflow: overlay` a legacy alias of `auto`
* URL: https://drafts.csswg.org/css-overflow-3/#valdef-overflow-auto

### Design reviews and vendor positions

* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/768

### Anything else we need to know

Since I believe Safari does not support `overflow:overlay`, the change would involve merely adding `overlay` as a legacy alias of `auto`.

**Comment by hober** [comment]
I'm not sure what to do with this request. The CSS WG resolved to make `overflow: overlay` an alias for `overflow: auto` & folk from each engine participated in that decision (@smfr from WebKit). What's your request, @chrishtr?

**Comment by chrishtr** [comment]
Hi @hober, the request is just to make sure WebKit is good with that change and plans to implement the legacy alias.

**Comment by hober** [comment]
> Hi @hober, the request is just to make sure WebKit is good with that change

@smfr said as much in the CSS WG meeting

> and plans to implement the legacy alias.

https://trac.webkit.org/changeset/236341/webkit
