### ISSUE TITLE
AbortSignal.any()

### ISSUE THREAD

**Issue by shaseley** [WebKit/standards-positions#166]
### WebKittens

@annevk

### Title of the spec

AbortSignal.any()

### URL to the spec

https://github.com/whatwg/dom/pull/1152

### URL to the spec's repository

https://github.com/whatwg/dom

### Issue Tracker URL

https://github.com/shaseley/abort-signal-any/issues

### Explainer URL

https://github.com/shaseley/abort-signal-any

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/737

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/774

### Description

`AbortSignal.any(signals)` returns an AbortSignal that is aborted when any of the source signals are aborted. Developers can use this to combine independent abort sources, e.g. timeouts specified with `AbortSignal.timeout()` and signals associated with user input, and pass them to async APIs like `fetch()`.

**Memory management**: composite signals (those returned by this API) must be kept alive while they can be aborted (by one of the sources) and have registered 'abort' event listeners or pending abort algorithms (see GC note in the spec PR). Implementing this API in userland has proved [difficult to do without leaks](https://github.com/whatwg/dom/issues/920), e.g. because of lack of knowledge about pending abort algorithms, but can be done by the browser where we have more visibility.

To implement the memory management in Chromium, we needed to clean up handling of pending abort algorithms, specifically making sure they get removed when they can no longer have an effect (e.g. when all related `fetch` state has been GCed). See also [this issue](https://github.com/shaseley/abort-signal-any/issues/4).

**Comment by annevk** [comment]
This is a good idea and increases symmetry between abort signals and promises. I suggest we mark this as "position: support" one week from now.
