### ISSUE TITLE
Zstandard compression format for Content-Encoding

### ISSUE THREAD

**Issue by nidhijaju** [WebKit/standards-positions#168]
### WebKittens

@annevk @ekinnear

### Title of the spec

Zstd Content-Encoding

### URL to the spec

https://datatracker.ietf.org/doc/html/rfc8878

### Explainer URL

https://docs.google.com/document/d/1aDyUw4mAzRdLyZyXpVgWvO-eLpc4ERz7I_7VDIPo9Hc/edit?usp=sharing

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/775

### Radar URL

rdar://28546450

### Description

[Zstandard](https://facebook.github.io/zstd/), or "zstd", is a data compression mechanism, described in [RFC8878](https://datatracker.ietf.org/doc/html/rfc8878), providing high compression ratios. The proposal is to add "zstd" to the tokens in the `Accept-Encoding` header, and decompress with Zstandard when the token is seen in the `Content-Encoding` header. It is anticipated to make pages load faster and reduce serving costs, by reducing CPU and/or bandwidth consumption, especially for dynamic content. 

Chrome is currently evaluating implementing this, and is interested in other browsers' position on the specification.

**Comment by ekinnear** [comment]
This may depend on support by the network stacks below WebKit, but additional content encodings that offer better compression can potentially lead to improvements in user visible performance. That is worth exploring, and measuring the impact in the real-world while evangelizing to increase deployment offers an opportunity to deliver wins for end users.

As such, I propose we label this with `position: support` 7 days from now.

**Comment by krassx** [comment]
Hi, is there any progress on bringing the Zstandard support to WebKit and consequently to Safari? According to [caniuse](https://caniuse.com/?search=zstd), Safari is the only one (of a major browsers) lacking support for zstd at the moment of writing.

I've been evaluating zstd for quite a while and it seems to be a good replacement in various scenarios for gzip, but the absence of support in all major browsers prevent switching to it.

Thank you in advance.

**Comment by ekinnear** [comment]
Hi @krassx! We continue to evaluate bringing Zstandard support to WebKit and are excited to hear that it may be delivering user-visible benefits for loading performance. Thanks for the note of support, feedback on what would be most helpful and beneficial is always appreciated!

**Comment by tats-u** [comment]
https://bugs.webkit.org/show_bug.cgi?id=279815

Posted an issue

**Comment by sandstrom** [comment]
Another vote for zstd here! 😄 

It's quite a bit faster:

![image](https://github.com/user-attachments/assets/ea14a182-f09f-4e6e-a65a-8e6e32fedcf9)

(source: https://facebook.github.io/zstd/#benchmarks)

**Comment by tats-u** [comment]
@sandstrom You should have posted it on the Bugzilla instead of here.

**Comment by ekinnear** [comment]
Thank you all for the energy and support here! Zstandard is now supported as of Safari 26.3 when running on OS versions 26.3 or later. Please do [file a bug](https://feedbackassistant.apple.com) for any issues that you find, it really helps us fix them.
