### ISSUE TITLE
FedCM bundle: LoginHint, Context, and User Info extensions

### ISSUE THREAD

**Issue by npm1** [WebKit/standards-positions#175]
### WebKittens

Not sure (whoever attends FedID CG meetings, if any)

### Title of the spec

FedCM bundle: LoginHint, Context, and User Info extensions

### URL to the spec

https://fedidcg.github.io/FedCM/

### URL to the spec's repository

https://github.com/fedidcg/FedCM

### Explainer URL

https://github.com/fedidcg/FedCM/issues/382

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/839

### Description

See also these two explainers:

* https://github.com/fedidcg/FedCM/issues/426
* https://github.com/fedidcg/FedCM/issues/456

This entry covers a few extensions to the FedCM API:

* With LoginHint, the RP can specify a hint about the user account they want displayed in the FedCM UI. Accounts which do not match the hint are not displayed. This is mainly used to provide a better UX for returning users.

* The UserInfo extension allows the IDP to personalize the login experience for returning users, for instance via personalized buttons. After the user has used FedCM with a given IDP on some RP site, this API provides some information about the user accounts to the IDP on subsequent visits to the RP.

* With the context parameter, the IDP can request for the FedCM dialog to show a different title than “Sign in”, to improve the message being displayed to the user in the FedCM UI.

See the explainers for more details.

**Comment by marcoscaceres** [comment]
Closing in favor or https://github.com/WebKit/standards-positions/issues/309 as we have never given a position of the actual FedCM spec.
