### ISSUE TITLE
Detect UA Transitions on Same-Document Navigations

### ISSUE THREAD

**Issue by khushalsagar** [WebKit/standards-positions#176]
### WebKittens

@smfr

### Title of the spec

Detect UA Transitions on Same-Document Navigations

### URL to the spec

https://github.com/whatwg/html/issues/8782

### Explainer URL

https://github.com/WICG/view-transitions/blob/main/default-ua-transitions.md#detecting-ua-transition

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/834

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/783

### Description

This API would help with issues like [this](https://stackoverflow.com/questions/66867737/iphone-safari-detect-swipe-navigation). Chromium is planning to ship similar browser UX and we're looking forward to fixing this problem in an interoperable way.

**Comment by annevk** [comment]
Having discussed this with colleagues this seems okay to us.

I suggest we label this as "position: support" one week from now.
