### ISSUE TITLE
Motion Path

### ISSUE THREAD

**Issue by danielsakhapov** [WebKit/standards-positions#187]
### Title of the spec

Motion Path

### URL to the spec

https://drafts.fxtf.org/motion/

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/802

### Description

The spec has been reworked, so requesting for the signal from you as it is a part of Interop 2023.

**Comment by nt1m** [comment]
We generally support the updated spec, will mark as support in one week pending objections.
