### ISSUE TITLE
Re-introduction of Media Queries (and srcset/sizes) in Source Elements

### ISSUE THREAD

**Issue by jernoble** [WebKit/standards-positions#190]
### WebKittens

@jernoble, @ericcarlson, @jyavenard

### Title of the spec

HTML Video Element: Proposal For Reintroduction of Media (and srcset/sizes) in Source Elements

### URL to the spec

https://html.spec.whatwg.org/

### URL to the spec's repository

https://github.com/whatwg/html

### Issue Tracker URL

https://github.com/whatwg/html/issues/6363

### Explainer URL

https://github.com/filamentgroup/html-video-responsive

### Description

The GitHub issue above tracks the re-introduction of media queries to `<source>` used by `<audio>` and `<video>` in the [resource selection algorithm](https://html.spec.whatwg.org/multipage/media.html#concept-media-load-algorithm) for [media elements](https://html.spec.whatwg.org/multipage/media.html#media-elements).

Media Queries (via the `media=` attribute to `<source>`) were previously specified in HTML, but were removed from the spec. Subsequent standardization of the `<picture>` element re-used the `<source>` element, [including the `media=` attribute](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-source-media). Currently, the resource selection algorithm makes no mention of the `media=` attribute, and the [specification of the `source` element](https://html.spec.whatwg.org/multipage/embedded-content.html#the-source-element) explicitly forbids the use of [srcset](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-source-srcset), [sizes](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-source-sizes), and [media](https://html.spec.whatwg.org/multipage/embedded-content.html#attr-source-media) attributes when the `source`'s parent is a media element.

WebKit never removed support for Media Queries from its implementation of `HTMLMediaElement`.  This issue tracks WebKit's public position on the re-inclusion of Media Queries, as well as the addition of support for `srcset` and `sizes`.

**Comment by jernoble** [comment]
Implementer hat on, I would argue WebKit should support this proposed re-introduction. We never removed support for media queries, but as the only implementor and with that implementation existing outside the specification, most authors resort to javascript for the same functionality.

**Comment by hober** [comment]
Given @jernoble's remarks, I plan to mark this as `position: support` in a week unless this discussion takes an unforeseen turn.

**Comment by Ghostavio** [comment]
Hey, I'm currently experiencing problems with this on Safari Version 18.5 (20621.2.5.11.8)
The source element with a media attribute seems to be ignored and skipped completely.
Wondering if anything changed.

**Comment by nt1m** [comment]
> Hey, I'm currently experiencing problems with this on Safari Version 18.5 (20621.2.5.11.8) The source element with a media attribute seems to be ignored and skipped completely. Wondering if anything changed.

Consider filing a bug on bugs.webkit.org ideally with a testcase :)
