### ISSUE TITLE
CSS same-origin cross-document view-transition

### ISSUE THREAD

**Issue by noamr** [WebKit/standards-positions#193]
### WebKittens

@nt1m @smfr 

### Title of the spec

CSS View Transitions, Level 2

### URL to the spec

https://github.com/WICG/view-transitions/blob/main/cross-doc-explainer.md

### URL to the spec's repository

https://github.com/w3c/csswg-drafts

### Explainer URL

https://github.com/WICG/view-transitions/blob/main/cross-doc-explainer.md

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/851

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/677

### Description

This is an extension of #48, which is still pending a position.
The spec is not up yet, it's in early TAG review.

**Comment by nt1m** [comment]
We will mark this proposal as support pending objections. The individual parts are reasonably simple and stack nicely on top of view transitions level 1.
