### ISSUE TITLE
BYOB support for Fetch

### ISSUE THREAD

**Issue by nidhijaju** [WebKit/standards-positions#194]
### WebKittens

@annevk

### Title of the spec

BYOB support for Fetch

### URL to the spec

https://fetch.spec.whatwg.org/#http-network-fetch

### URL to the spec's repository

https://github.com/whatwg/fetch

### Description

The proposal is to make Response.body be a readable byte stream instead of a "default" readable stream. This enables it to be used with bring-your-own-buffer (BYOB) readers, reducing garbage collection overhead and copies. The spec PR for this was landed at https://github.com/whatwg/fetch/pull/1593.

Firefox has already shipped this in 2022 (see https://github.com/whatwg/fetch/issues/267#issuecomment-1350303670), and implementation is in progress for Chrome. The corresponding ChromeStatus entry for this feature is at https://chromestatus.com/feature/5192003450568704.

**Comment by annevk** [comment]
I discussed this with colleagues and this looks good to us. I suggest we label this as "position: support" one week from now.
