### ISSUE TITLE
Deprecate TLS SHA-1 server signatures

### ISSUE THREAD

**Issue by dadrian** [WebKit/standards-positions#196]
### WebKittens

@bailey

### Title of the spec

Deprecating MD5 and SHA-1 Signature Hashes in TLS 1.2 and DTLS 1.2

### URL to the spec

https://www.rfc-editor.org/rfc/rfc9155.html

### Description

Chrome Status Entry: https://chromestatus.com/feature/4832850040324096

Chrome plans on removing support for SHA1 in server signatures in TLS. SHA1 in server certificates has been disallowed for years. SHA1 in client certificates are not affected by this change. MD5 is already disallowed.

(We think this falls outside of W3C process purview, but are circulating among other browsers regardless)

**Comment by tfpauly** [comment]
I suggest labeling this as "position: support" one week from now, allowing for feedback.

This is a document which we've watched progress through the IETF in the TLS WG, and have supported through that process.

**Comment by tfpauly** [comment]
Yes, please. Can you mark it?

**Comment by dadrian** [comment]
I don't have permission to add a label.
