### ISSUE TITLE
import.meta.resolve()

### ISSUE THREAD

**Issue by marcoscaceres** [WebKit/standards-positions#2]
## Request for position on an emerging web specification

* WebKittens who can provide input: 

### Information about the spec

* Spec Title: HTML
* Spec URL: 
* GitHub repository: 
* Issue Tracker (if not the repository's issue tracker): 
* Explainer (if not README.md in the repository): 

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: 

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

On [WebKit-dev](https://lists.webkit.org/pipermail/webkit-dev/2022-June/032290.html), @domenic proposed:

We're proposing a small additional function to add to the HTML Standard, named import.meta.resolve(). See the PR [1] and a mini-explainer [2]. Gecko folks have reviewed the PR and contributed to the discussion, but any thoughts from WebKit would be very welcome.

We're hoping to ship in Chrome within the next few weeks, and I imagine web developers would love it if you were to also implement. We have a basic implementation and web platform tests you may find useful [3].

Thanks,
Domenic

[1]: https://github.com/whatwg/html/pull/5572
[2]: https://gist.github.com/domenic/f2a0a9cb62d499bcc4d12aebd1c255ab
[3]: https://chromium-review.googlesource.com/c/chromium/src/+/3456729

**Comment by Constellation** [comment]
This looks reasonable. Our internal implementation starts with async `resolve` function, and eventually we converted it into sync `resolve` function.

**Comment by domenic** [comment]
Thanks @marcoscaceres and @Constellation!

I've merged the HTML spec PR, so there is now a spec at https://html.spec.whatwg.org/#hostgetimportmetaproperties . Tests are at https://github.com/web-platform-tests/wpt/pull/34188 and I filed a WebKit bug at https://bugs.webkit.org/show_bug.cgi?id=242163 . Let me know if there's anything else I can help with.

**Comment by marcoscaceres** [comment]
Thanks @domenic! That's great. And thanks also for filling the WebKit bug. 🙏

**Comment by Constellation** [comment]
https://github.com/WebKit/WebKit/commit/78c6d6d7b596a5953915f8066a5e75d19eda8411 Landed into WebKit.

**Comment by hober** [comment]
Closing as we've identified our position.
