### ISSUE TITLE
border-boundary CSS property

### ISSUE THREAD

**Issue by nt1m** [WebKit/standards-positions#201]
### WebKittens

@smfr 

### Title of the spec

CSS Round Display 1 Module

### URL to the spec

https://www.w3.org/TR/css-round-display-1/#border-boundary-property

### Description

According to https://webkit.org/css-status/, this is "not considering", but I'm about to remove those statuses from the page, so creating a standards position to record the position.

**Comment by othermaciej** [comment]
Let's discuss before assigning a position.

**Comment by annevk** [comment]
Discussing this with colleagues we're "position: neutral" on this idea. I suggest we resolve it as such unless someone objects within a week.
