### ISSUE TITLE
contain-intrinsic-size: auto none syntax support

### ISSUE THREAD

**Issue by vmpstr** [WebKit/standards-positions#205]
### Title of the spec

CSS Sizing, Level 4

### URL to the spec

https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-size

### URL to the spec's repository

https://github.com/w3c/csswg-drafts/

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/827

### Description

The resolution to add contain-intrinsic-size: auto none syntax is a part of the following resolution:
https://github.com/w3c/csswg-drafts/issues/8407#issuecomment-1440466558

**Comment by annevk** [comment]
Per https://github.com/w3c/csswg-drafts/issues/8407#issuecomment-1440466558 onward it seems there's still an unresolved question from Emilio here?

cc @smfr @nt1m

**Comment by nt1m** [comment]
@rwlbuis @cathiechen

**Comment by vmpstr** [comment]
> Per [w3c/csswg-drafts#8407 (comment)](https://github.com/w3c/csswg-drafts/issues/8407#issuecomment-1440466558) onward it seems there's still an unresolved question from Emilio here?

Do you mean the question in this comment: https://github.com/w3c/csswg-drafts/issues/8407#issuecomment-1496753402?

That's clarifying a different part of the resolution: whether content-visibility: auto adds the auto keyword to computed value of contain-intrinsic-size or to the used value.

The request for position here is just the "contain-intrinsic-size: auto none" support.

However, you're right that the question will need to be resolved before file a position request for the content-visibility: auto and contain-intrinsic-size interaction

**Comment by nt1m** [comment]
I think this is generally fine, see: https://github.com/WebKit/WebKit/pull/15369

Thanks Rob for implementing!

**Comment by nt1m** [comment]
Closing as the WebKit patch landed
