### ISSUE TITLE
ServiceWorker static routing API

### ISSUE THREAD

**Issue by yoshisatoyanagisawa** [WebKit/standards-positions#206]
### WebKittens

@annevk

### Title of the spec

ServiceWorker static routing API

### URL to the spec

https://w3c.github.io/ServiceWorker/

### URL to the spec's repository

https://github.com/w3c/ServiceWorker

### Issue Tracker URL

https://github.com/w3c/ServiceWorker/issues/1373

### Explainer URL

https://github.com/WICG/service-worker-static-routing-api

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/863

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/828

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=269893

### Description

This API allows developers to configure the routing, and allows them to offload simple things ServiceWorkers do. If the condition matches, the navigation happens without starting ServiceWorkers or executing JavaScript, which allows web pages to avoid performance penalties due to ServiceWorker interceptions.

Starting ServiceWorkers is known to be a slow process, and web users need to wait for its startup if the ServiceWorker intercepts loading the page resources. At the same time, the ServiceWorker brings flexibility to the transport layer, and it behaves as a client-side proxy. Developers can implement offline support or provide client-side content modification with it. Currently, ServiceWorkers intercept all requests for pages within their scope, which brings a performance penalty within the scope.

Venue: we plan to do incubation work in the discussion tracker of w3c/ServiceWorker, despite hosting the explainer in a private repository.

**Comment by annevk** [comment]
In principle this idea seems reasonable, but this builds upon `URLPattern` (discussed in #61) which despite repeated requests hasn't been standardized.

**Comment by yoshisatoyanagisawa** [comment]
[URLPattern](https://urlpattern.spec.whatwg.org/) became the web standard, and it is actively [maintained](https://github.com/whatwg/urlpattern) now.

Do you have any other concerns?

**Comment by yoshisatoyanagisawa** [comment]
FYI, but the ServiceWorker static routing API has been merged to the spec.
https://github.com/w3c/ServiceWorker/commit/8d4b9dfbeea511955a259949f2bc01227f995fe2

**Comment by annevk** [comment]
I discussed this with colleagues and this seems like a reasonable addition to us. Thanks for working on it!

As such I suggest we resolve this as "position: support" one week from now.
