### ISSUE TITLE
Web Charts

### ISSUE THREAD

**Issue by AdamSobieski** [WebKit/standards-positions#207]
### Title of the spec

Web Charts

### URL to the spec

https://github.com/WICG/proposals/issues/97

### Explainer URL

https://github.com/WICG/proposals/issues/97

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/829

### Description

The _**Web Charts**_ proposal intends to add a new HTML [media element](https://html.spec.whatwg.org/multipage/media.html#media-element), `<chart>`, alongside the `<audio>` and `<video>` elements.

Charts can provide interactive visualizations for static data as well as for time-based, dynamic, streaming data. Scenarios for this latter case, consuming "data video", include displaying streaming data from: sensors, business intelligence and analytics, and stock markets.

Accordingly, the proposed `<chart>` element would be conceptually derived from the `<video>` element, utilizing most or all of its attributes, and extending its content model. In this approach, any eventual `HTMLChartElement` interface would extend `HTMLMediaElement`.

For scenarios involving the visualization of static data, here are some markup examples:

```xml
<chart src="data.csv" width="600" height="400">
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
</chart>
```

```xml
<chart width="600" height="400">
  <source type="text/csv" src="data.csv" />
  <source type="text/tsv" src="data.tsv" />
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
</chart>
```

In these above examples, the provided scripting logic processes the selected input data into interactive content, e.g., HTML, SVG, Canvas, WebGL, or WebGPU content, in the shadow DOM.

Next, we can add configuration settings for the provided scripting logic to consume utilizing the [data block](https://html.spec.whatwg.org/multipage/scripting.html#data-block) capabilities of `<script>` elements when they are provided content of a type other than `text/javascript`.

```xml
<chart src="data.csv" width="600" height="400">
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
</chart>
```

```xml
<chart width="600" height="400">
  <source type="text/csv" src="data.csv" />
  <source type="text/tsv" src="data.tsv" />
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
</chart>
```

Next, for time-based, dynamic, streaming data scenarios, here are some markup examples. In the following examples, the MIME types of `video/mp4` and `video/webm` are utilized as placeholders.

```xml
<chart src="data-video.m3u8" poster="loading.png" autoplay="true" controls="true" width="600" height="400">
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
</chart>
```

```xml
<chart poster="loading.png" autoplay="true" controls="true" width="600" height="400">
  <source type="video/mp4" src="data-video.mp4" />
  <source type="video/webm" src="data-video.webm" />
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
</chart>
```

Finally, we can add a `<style>` element so that charts could provide custom styling instead of only being able to utilize the style of their containing documents.

```xml
<chart src="data-video.m3u8" poster="loading.png" autoplay="true" controls="true" width="600" height="400">
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
  <style  src="custom.css" />
</chart>
```

```xml
<chart poster="loading.png" autoplay="true" controls="true" width="600" height="400">
  <source type="video/mp4" src="data-video.mp4" />
  <source type="video/webm" src="data-video.webm" />
  <script type="text/javascript" src="https://cdn.webcache.org/bar-chart.js" />
  <script type="text/json" src="settings.json" />
  <style  src="custom.css" />
</chart>
```

**Comment by marcoscaceres** [comment]
I guess the main question I have is: how does it semantically differ  from `<figure>` or `<picture>` or even `<video>`? 

Media-capable HTML elements are generally used as rendering containers/viewports, however, this seems to rely on JS to render the chart which defeats the purpose of having the element. 

Consider, to meet the bar for a new HTML element, this should just work:

```HTML
<!-- this should render something meaningful without JS -->
<chart src="chart.format"></chart>
``` 

Similarly, with the `<video>` example, it seems to replicate existing capabilities that are already part of `<video>` but without significant usability, accessibility, or internationalization advantages for end users.

**Comment by AdamSobieski** [comment]
@marcoscaceres, 

One reason for a developer-specified scripting logic approach is that there are so many different types of charts.

According to [Wikipedia](https://en.wikipedia.org/wiki/Chart), there are, to consider, the common chart types: histograms, bar charts, pie charts, and line charts. There are also: timeline charts, organizational charts, tree charts, flow charts, area charts, cartograms, pedigree charts, and radial tree charts. There are also the less-common chart types: bubble charts, polar area diagrams, waterfall charts, radar charts, tree maps, streamgraphs, and gapcharts. Beyond all of these types of charts, data visualization designers can also get creative.

The capabilities to be able to provide settings or configuration and to be able to provide custom styling would enhance scripts' reusability and, thus, their cacheability. Would Web developers reutilize scripts from third-party providers, browsers could efficiently cache these resources.

With respect to useability, accessibility, and internationalization, these would be features provided by the scripts which would provide the visualizations in the shadow DOM for the input data.

As for how a `<chart>` element would differ from elements like `<img>`, `<picture>`, or `<video>`, charts' scripting logic would create and modify visualizations for both static or streaming data utilizing HTML, SVG, Canvas, WebGL, or WebGPU in the shadow DOM. In these regards, charts would be interactive, resizable, and reflowable. Charts would be capable of providing mouseover effects, supporting end-users selecting subcontents, providing context menus, supporting drag-and-drop scenarios, and more.

While it could be useful to have something like:

```xml
<chart src="chart.format" />
```

Such a format, maybe a "ChartML", would, I think, include the same main points considered in the proposal:

1. Included or referenced input data files or streams in one or more data formats.
2. Scripting logic for visualizing the static or streaming data in HTML, SVG, Canvas, WebGL, or WebGPU in the shadow DOM.
3. Settings or configuration for the scripting logic.
4. Styling.

Instead of providing a script, per point 2, a "ChartML" resource could specify a well-known type of data visualization, the type of the chart, by URI, though I, for one, consider there to be significant room for variation with respect to each types' implementation and the set of types of data visualizations to be open-ended.

**Comment by rniwa** [comment]
This seems like a sort of a thing a custom element can be useful. I don't see a value in standardizing element that then requires scripts to do everything.

**Comment by AdamSobieski** [comment]
@rniwa, yes, something like a `<web-chart>` [custom element](https://html.spec.whatwg.org/multipage/custom-elements.html) could be useful. Such a custom element could provide a framework with which compatible referenced scripts would interoperate. Also, the "data video" concepts for time-based, streaming data visualization scenarios could be implemented, or at least prototyped, utilizing [WebVTT](https://www.w3.org/TR/webvtt1/)-based text tracks in existing video formats. These text tracks could, for example, contain update operations for memory-resident [IndexedDB](https://www.w3.org/TR/IndexedDB/) tables. [Reactive](https://en.wikipedia.org/wiki/Reactive_programming) solutions for IndexedDB databases exist.

To the second point, also possible are uses of a new attribute, e.g., `kind`, on `<chart>` elements utilizing a controlled vocabulary:

```xml
<chart kind="bar" src="data.csv" width="600" height="400" />
```

```xml
<chart kind="bar" width="600" height="400">
  <source type="text/csv" src="data.csv" />
  <source type="text/tsv" src="data.tsv" />
</chart>
```

**Comment by marcoscaceres** [comment]
The proposal is interesting and we acknowledge that graphs are an extremely useful means to convey information on the web. However, the proposal doesn't seem to add enough functionality to warrant the standardization a new HTML element. 

Given the above points, I'm going to say WebKit is "opposed" to this proposal as is, as:

 * it relies on script to do the heavy lifting (or to work at all!), so it's probably better suited to be a custom element. 
 * it simply wraps and depends  on existing HTML elements (ing, svg, canvas, etc.), which do the actual rendering and handle functionality. 
 * Seems add limited user benefit in terms of usability, accessibility, and internationalization. 
 * doesn't provide developers with significant ergonomic improvements over what they already have to work with (i.e., they would still need to manipulate a 2D context or SVG file to draw/animate the graph etc.)
 * there is no standard format for charts (which is probably a good thing, as JSON, CSV, XML etc. can all be relatively easily fetched and used as data sources)

Further input welcome from other folks, particularly if there is disagreement with my assessment above. If not, we will move to make "opposed" WebKit's official position on this proposal.
