### ISSUE TITLE
exclusive accordions with <details name="">

### ISSUE THREAD

**Issue by dbaron** [WebKit/standards-positions#209]
### WebKittens

@annevk

### Title of the spec

HTML: exclusive accordions with `<details name="">`

### URL to the spec

https://github.com/whatwg/html/pull/9400

### URL to the spec's repository

https://github.com/openui/open-ui

### Explainer URL

https://open-ui.org/components/accordion.explainer

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/831

### Description

I hope the above [explainer](https://open-ui.org/components/accordion.explainer) and [HTML PR](https://github.com/whatwg/html/pull/9400) have the information you need to know.

I'm also hoping to make progress on related (but separate) work to improve styleability of `<details>` and to improve some existing accessibility issues with it.

**Comment by annevk** [comment]
I discussed this with colleagues and we're supportive of this feature. It'll be marked as "position: support" one week from now, provided there's no further feedback.
