### ISSUE TITLE
@starting-style CSS Rule

### ISSUE THREAD

**Issue by lilles** [WebKit/standards-positions#210]
### Title of the spec

CSS Transitions: @starting-style

### URL to the spec

https://drafts.csswg.org/css-transitions-2/#defining-before-change-style-the-starting-style-rule

### Explainer URL

https://github.com/chrishtr/rendering/blob/master/entry-exit-animations.md

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/829

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/833

### Description

The explainer is outdated since it uses the :initial pseudo class that was later made into an @initial rule, and later renamed @starting-style  by the CSSWG.

**Comment by nt1m** [comment]
I'll mark this as support pending objections next week given this is an useful feature to developers, and:
https://github.com/WebKit/WebKit/pull/23431
https://github.com/WebKit/WebKit/pull/23413
https://github.com/WebKit/WebKit/pull/23044

**Comment by Ahmad-S792** [comment]
It is now enabled by default as well: https://github.com/WebKit/WebKit/commit/1544606a8541c44e64d73ae4693c90da45ca6402
