### ISSUE TITLE
Request for position: `dialogmodaltarget` attribute

### ISSUE THREAD

**Issue by keithamus** [WebKit/standards-positions#213]
### WebKittens

@annevk @rniwa

### Title of the spec

HTML `dialogmodaltarget` attribute

### URL to the spec

https://github.com/whatwg/html/pull/9456

### URL to the spec's repository

https://github.com/whatwg/html/pull/9456

### Explainer URL

https://github.com/whatwg/html/pull/9456

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=258562

### Description

This spec adds a `dialogmodaltarget` attribute to button elements. Similar to `popovertarget`, `dialogmodaltarget` takes an IDREF and calls `showModal()` or `close()` on the idref element, when the button is clicked. It also specifies the reflected `dialogModalTargetElement` attribute (which allows for cross-root assignment).

**Comment by nt1m** [comment]
This proposal has been deprecated by the invoker buttons proposal, closing.
