### ISSUE TITLE
CSS Properties and Values API Level 1

### ISSUE THREAD

**Issue by bramus** [WebKit/standards-positions#22]
### Information about the spec

* Spec Title: CSS Properties and Values API Level 1
* Spec URL: https://www.w3.org/TR/css-properties-values-api-1/
* GitHub repository: https://github.com/w3c/css-houdini-drafts
* Issue Tracker: https://github.com/w3c/css-houdini-drafts/issues

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/402
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/93 — Worth Prototyping

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=189692
* Radar: rdar://30061591

### Anything else we need to know

- https://web.dev/at-property/
- https://developer.mozilla.org/en-US/docs/Web/API/CSS_Properties_and_Values_API

**Comment by hober** [comment]
cc @rniwa @smfr @anttijk

**Comment by nt1m** [comment]
This is shipping in STP at the moment and is part of Interop 2023. It makes CSS variables more powerful and notably in combination with animations.

**Comment by hober** [comment]
Closing as we've identified our position.
