### ISSUE TITLE
content-visibility: auto forces contain-intrinsic-size: auto

### ISSUE THREAD

**Issue by vmpstr** [WebKit/standards-positions#228]
### Title of the spec

content-visibility: auto forces contain-intrinsic-size: auto

### URL to the spec

https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-size

### URL to the spec's repository

https://github.com/w3c/csswg-drafts/

### Description

This is a proposal for `content-visibility: auto` to force `contain-intrinsic-size` to obtain the `auto` keyword. This has been [resolved in CSSWG](https://github.com/w3c/csswg-drafts/issues/8407#issuecomment-1440466558). It has also been [implemented by Mozilla](https://hg.mozilla.org/mozilla-central/rev/af2192d1c537)

**Comment by nt1m** [comment]
https://github.com/WebKit/WebKit/pull/16226 is implementing this.
