### ISSUE TITLE
css-ui `form-sizing` property

### ISSUE THREAD

**Issue by tkent-google** [WebKit/standards-positions#231]
### Title of the spec

css-ui `form-sizing` property

### URL to the spec

https://github.com/w3c/csswg-drafts/issues/7542#issuecomment-1542505774

### Description

We're going to introduce `form-sizing` property in probably css-ui.
Web developers can make auto-growing text form controls with it.

We don't have a spec pull-request yet.

**Comment by annevk** [comment]
Overall colleagues and I are very supportive of making it easier to style existing form controls.

As @nt1m outlined in https://github.com/w3c/csswg-drafts/issues/7542#issuecomment-1685352461 the naming could be a little clearer.

**Comment by lukewarlow** [comment]
https://drafts.csswg.org/css-ui/#field-sizing

Just as an fyi this has been renamed field-sizing with fixed and content being the values.

**Comment by lukewarlow** [comment]
For ease of linking between them https://github.com/mozilla/standards-positions/issues/849 is the mozilla position.

**Comment by myfonj** [comment]
Also cross-linking WebKit Bugzilla issue: https://bugs.webkit.org/show_bug.cgi?id=264720 (missing from the description at this point).
