### ISSUE TITLE
CSS Ruby Annotation Layout Module Level 1

### ISSUE THREAD

**Issue by tkent-google** [WebKit/standards-positions#232]
### Title of the spec

CSS Ruby Annotation Layout Module Level 1

### URL to the spec

https://drafts.csswg.org/css-ruby-1/

### URL to the spec's repository

https://github.com/w3c/csswg-drafts

### Description

This is for the whole css-ruby specification.

* Myles already said "positive" in https://lists.webkit.org/pipermail/webkit-dev/2020-September/031417.html. This issue was filed because the standards-positions repository is helpful for Chromium's ship process.
* Firefox already shipped almost all the features in the specification.
* Chromium is positive on some parts of the specification.

**Comment by annevk** [comment]
I discussed this with colleagues and we're supportive of this effort (as Myles already stated). I suggest we close this one week from now with "position: support".
