### ISSUE TITLE
Extending the autocomplete attribute to all editing host elements

### ISSUE THREAD

**Issue by sanketj** [WebKit/standards-positions#236]
### WebKittens

@annevk

### Title of the spec

HTML Living Standard

### URL to the spec

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofilling-form-controls:-the-autocomplete-attribute

### Explainer URL

https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/AutocompleteContentEditable/explainer.md

### Description

Expand the definition of the autocomplete attribute to allow UAs to provide autocomplete capabilities in editing host elements.

**Comment by sanketj** [comment]
Related discussion: https://github.com/whatwg/html/issues/9065

**Comment by stephanieyzhang** [comment]
This proposal has been updated. [Here's the new issue](https://github.com/WebKit/standards-positions/issues/308).

@sanketj is currently out of office, so we are unable to update/close out this existing issue until he's back. Created a new one to continue to get things rolling.

**Comment by marcoscaceres** [comment]
@stephanieyzhang, this proposal is different, right? Should we still look at this one?

**Comment by stephanieyzhang** [comment]
@marcoscaceres This proposal was the v1 of the ['writingsuggestions' attribute proposal](https://github.com/WebKit/standards-positions/issues/308) and is now outdated. Please look at the linked proposal instead - thanks!
