### ISSUE TITLE
hidden=until-found attribute and beforematch event

### ISSUE THREAD

**Issue by josepharhar** [WebKit/standards-positions#246]
### Title of the spec

hidden=until-found attribute and beforematch event

### URL to the spec

https://html.spec.whatwg.org/multipage/interaction.html#the-hidden-attribute

### URL to the spec's repository

https://github.com/whatwg/html

### Explainer URL

https://github.com/WICG/display-locking/blob/main/explainers/hidden-content-explainer.md

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/511

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/612

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=238266

### Description

I originally requested feedback for this here: https://lists.webkit.org/pipermail/webkit-dev/2022-March/032142.html

This is closely related to https://github.com/WebKit/standards-positions/issues/247

This feature builds on `content-visibility:hidden` and a portion of `content-visibility:auto` in order to work.

**Comment by annevk** [comment]
Colleagues and I discussed this and think it's a good feature. I suggest we mark this as "position: support" one week from now. Thanks for checking in Joey!
