### ISSUE TITLE
Auto-expanding details elements

### ISSUE THREAD

**Issue by josepharhar** [WebKit/standards-positions#247]
### Title of the spec

Auto-expanding details elements

### URL to the spec

https://html.spec.whatwg.org/multipage/interaction.html#interaction-with-details-and-hidden=until-found

### URL to the spec's repository

https://github.com/whatwg/html

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/677

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/578

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=228843

### Description

This is closely related to https://github.com/WebKit/standards-positions/issues/246

This feature builds on `content-visibility:hidden` and a portion of `content-visibility:auto` in order to work.

**Comment by annevk** [comment]
Colleagues and I discussed this and are supportive of this feature. Therefore let's mark this as "position: support" one week from now.
