### ISSUE TITLE
FedCM API extension: Error API, AccountAutoSelectedFlag, HostedDomain and Revocation API

### ISSUE THREAD

**Issue by yi-gu** [WebKit/standards-positions#249]
### Title of the spec

FedCM API extension: Error API, AccountAutoSelectedFlag, HostedDomain and Revocation API 

### URL to the spec

https://fedidcg.github.io/FedCM/

### URL to the spec's repository

https://github.com/fedidcg/FedCM

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/893

### Description

We publish explainers as issues per request from Mozilla ([more details](https://github.com/w3ctag/design-reviews/issues/813#issuecomment-1466632934)). For explainers please see the first and second comments of [Error API](https://github.com/fedidcg/FedCM/issues/488), [AccountAutoSelectedFlag](https://github.com/fedidcg/FedCM/issues/497), [HostedDomain](https://github.com/fedidcg/FedCM/issues/427) and [Revocation](https://github.com/fedidcg/FedCM/issues/496).

Quick summary:
    - With the Error API, the browser can inform users with proper error messages when their sign-in request has failed.
    - With the AccountAutoSelected Flag API, the browser could help developers to determine if FedCM token requests were initiated with explicit user permission to improve their services.
    - With the Hosted Domain API, RP can choose to only show the accounts which are associated with a certain domain.
    - With the Revocation API, developers can revoke the connection between RP and IdP upon user request and update the browser to optimize the future flows. 

We have spec PRs for [Error API ](https://github.com/fedidcg/FedCM/pull/498) and [AccountAutoSelectedFlag API](https://github.com/fedidcg/FedCM/pull/500) since Chrome plans to ship them sooner than the other two.

**Comment by npm1** [comment]
Update: we also now have PRs for [domain hint](https://github.com/fedidcg/FedCM/pull/512) (renamed from hosted domain) and [disconnect](https://github.com/fedidcg/FedCM/pull/515) (renamed from revoke).

**Comment by marcoscaceres** [comment]
Closing in favor or https://github.com/WebKit/standards-positions/issues/309 as we have never given a position of the actual FedCM spec.
