### ISSUE TITLE
HTMLSelectElement `showPicker()`

### ISSUE THREAD

**Issue by lukewarlow** [WebKit/standards-positions#258]
### WebKittens

@annevk

### Title of the spec

HTMLSelectElement's showPicker()

### URL to the spec

https://github.com/whatwg/html/pull/9754

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/900

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/886

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=261814

### Description

The showPicker() method is a new addition to HTMLSelectElement which addresses a [common request from web developers](https://www.google.com/search?q=programmatically+open+select+site%3Astackoverflow.com): programmatically showing the option picker UI for a select element

**Comment by Ahmad-S792** [comment]
@pxlcoder & @rniwa - FYI and to share any input as well.

**Comment by annevk** [comment]
https://github.com/whatwg/html/pull/9754#issuecomment-1726093197 still applies.

**Comment by lukewarlow** [comment]
Implementation PR: https://github.com/WebKit/WebKit/pull/18479

**Comment by annevk** [comment]
I suggest we resolve this as "position: support" one week from now given that our concern has been addressed (non-rendered `select` elements won't work for now).
