### ISSUE TITLE
meta: add an issue form instead of current template

### ISSUE THREAD

**Issue by gsnedders** [WebKit/standards-positions#26]
See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by othermaciej** [comment]
What's the difference between an issue form and a template?

**Comment by karlcow** [comment]
@othermaciej It's a more evolved templating system using YAML adding a bit more constrains and checks.

> New, YAML configured issue forms enable maintainers to build structured forms with required fields and easy-to-follow steps so that they can capture every important detail. — [Issues forms beta for public repositories](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/), announced on July 2021
