### ISSUE TITLE
Vibration API (Second Edition)

### ISSUE THREAD

**Issue by MrBrain295** [WebKit/standards-positions#267]
### Title of the spec

Vibration API (Second Edition)

### URL to the spec

https://w3c.github.io/vibration/

### URL to the spec's repository

https://github.com/w3c/vibration/

### Issue Tracker URL

https://github.com/w3c/vibration/issues

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/907

### Description

In their words "The API is specifically designed to address use cases that require simple tactile feedback only. Use cases requiring more fine-grained control are out of scope for this specification. This API is not meant to be used as a generic notification mechanism. Such use cases may be handled using the Notifications API [[NOTIFICATIONS](https://w3c.github.io/vibration/#bib-notifications)] specification. In addition, determining whether vibration is enabled is out of scope for this specification."

**Comment by marcoscaceres** [comment]
I think the problem with the API is exactly the one described by API itself, in that it's both too simple: 

- It doesn't actually provide means to be tactually expressive;
-  it's too susceptible to being abused as a notification mechanism - hence the concern about user annoyance.
- it doesn't provide any description of what "vibrate" actually means, thus would lead to different "feels" across devices, platforms, etc. 

So it's not clear what the use case for this API is for or how it benefits users in a meaningful way.

**Comment by marcoscaceres** [comment]
Discussed with colleagues internally and they also pointed out that it wouldn't even be possible to support this API on Apple's native platforms (concern: integration).  

Taking what [I already wrote above](https://github.com/WebKit/standards-positions/issues/267#issuecomment-1767541211), and unless anyone from the WebKit community objects, we will be labeling this as "opposed" within a week or so.

**Comment by MrBrain295** [comment]
Is this good to close?

**Comment by MrBrain295** [comment]
@marcoscaceres could you please add the oppose label? Thanks!

**Comment by marcospgp** [comment]
Any chance this can be reconsidered? haptic feedback is a critical feature for web apps, and webkit is the only modern browser engine not implementing it: https://caniuse.com/vibration
