### ISSUE TITLE
Cross-Origin Embedder Policies - "credentialless"

### ISSUE THREAD

**Issue by adixon-adobe** [WebKit/standards-positions#268]
### WebKittens

@annevk

### Title of the spec

Cross-Origin Embedder Policies - "credentialless"

### URL to the spec

https://html.spec.whatwg.org/multipage/browsers.html#coep-credentialless

### URL to the spec's repository

https://github.com/whatwg/html

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/582

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/539

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=230550

### Description

This was previously filed by the Chromium team in June 2021 here: https://lists.webkit.org/pipermail/webkit-dev/2021-June/031898.html. This was subsequently merged into the HTML & Fetch specifications in November 2021. It also looks like Firefox will be adding support in their next release (119).

The Credentialless variant of Cross Origin Embedded Policy simplifies cross origin isolation, as existing third party scripts don't require changes unless they actually need headers that are omitted by the policy. With the require-corp variant, third party scripts must include the Cross-Origin-Resource-Policy: cross-origin header to work. In addition to requiring more coordination and third party changes, it also creates a new potential failure point with third party scripts if they accidentally remove the header.

**Comment by annevk** [comment]
I discussed this with colleagues and `Cross-Origin-Embedder-Policy: credentialless` seems like a reasonable addition to the web platform to us. As such we suggest resolving this as "position: support" one week from now.

Given the security-sensitive nature of this feature I feel like I should point out that the specification notes that Local Network Access (#163) and Opaque Response Blocking (#64) are pre-requisites here and thus if anyone were thinking of undertaking a WebKit implementation they would have to take that into account. (It might be tenable to only have one of those, though not ideal.)
