### ISSUE TITLE
WebGPU timestamp queries

### ISSUE THREAD

**Issue by beaufortfrancois** [WebKit/standards-positions#273]
### WebKittens

@mwyrzykowski

### Title of the spec

WebGPU timestamp queries

### URL to the spec

https://gpuweb.github.io/gpuweb/#timestamp

### URL to the spec's repository

https://github.com/gpuweb/gpuweb/

### Explainer URL

https://github.com/gpuweb/gpuweb/issues/614

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/918

### Description

* blink-dev Intent to Ship: https://groups.google.com/a/chromium.org/g/blink-dev/c/dtYJ0MQYMlU

**Comment by mwyrzykowski** [comment]
We consider this part of the specification when we considered our position on WebGPU generally (https://github.com/WebKit/standards-positions/issues/107).

Is there any further position for us to take here? We have no objections to the timestamps write specification in the current working draft of the specification.

**Comment by annevk** [comment]
Let's resolve it as a duplicate of #107 instead.
