### ISSUE TITLE
[css-cascade-5] Implement supports() for @import

### ISSUE THREAD

**Issue by danielsakhapov** [WebKit/standards-positions#279]
### Title of the spec

CSS Cascading and Inheritance: supports() for @import

### URL to the spec

https://drafts.csswg.org/css-cascade-5/#conditional-import

### Mozilla standards-positions issue URL

Positive, Firefox shipped this.

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=256180

### Description

Firefox has shipped it.
Chrome implemented, processing to ship.

**Comment by nt1m** [comment]
We think this is an useful feature and we have also recently implemented this: https://github.com/WebKit/WebKit/pull/23190

We will mark as support in a week pending objections.
