### ISSUE TITLE
File System Access API (Local Filesystem)

### ISSUE THREAD

**Issue by BenjaminAster** [WebKit/standards-positions#28]
### Information about the spec

* Spec Title: File System Access
* Spec URL: https://wicg.github.io/file-system-access/
* GitHub repository: https://github.com/WICG/file-system-access
* Issue Tracker (if not the repository's issue tracker): 
* Explainer (if not README.md in the repository): https://github.com/WICG/file-system-access/blob/main/EXPLAINER.md

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/154

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=231706
* Radar: `<rdar://problem/84484202>`

### Anything else we need to know

The File System Access API allows websites to directly interact with the computer's local files. Shipped in Chromium 86.

Note: I'm not talking about the Origin Private File System part of the File System Access API that has already been implemented in WebKit, but about the part that allows for direct access to local files.

**Comment by tomayac** [comment]
- WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=231706

**Comment by BenjaminAster** [comment]
@tomayac Thanks! I've now edited the issue to include these links.

**Comment by gsnedders** [comment]
See also https://github.com/WICG/file-system-access/issues/342 for where the parts of the WICG report got migrated into the WHATWG Storage Workstream, and https://github.com/WICG/file-system-access/issues/370 about removing the duplicated content from the WICG report.

cc @johnwilander @youennf

**Comment by annevk** [comment]
Colleagues and I have discussed this and don't see a way to grant access to the end user's local file system in a way that safeguards the end user's interests. Quite in line with the conclusion Mozilla reached in https://github.com/mozilla/standards-positions/issues/154.

We do think there might be ways that `<input type=file>` and https://wicg.github.io/entries-api/ could be integrated better with https://fs.spec.whatwg.org/.

Based on that I suggest we label this as "position: oppose" 7 days from now.

**Comment by hober** [comment]
Closing as we've identified our position.

**Comment by waynebloss** [comment]
Gee a trillion dollar company taking direction from Mozilla, a defunct “progressive” activist led organization which has a browser that nearly nobody is using? An organization that is propped up by your main competitor? When you don’t even trust them enough to let them run their own browser engine on your phone unless some government forces you to?

Makes total sense.

“We can’t figure out security for sandboxing file access unless you pay us 30%” - shocker!
