### ISSUE TITLE
HTML modules

### ISSUE THREAD

**Issue by o-t-w** [WebKit/standards-positions#285]
### Title of the spec

HTML Modules

### URL to the spec

https://github.com/WICG/webcomponents/blob/gh-pages/proposals/html-modules-explainer.md

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/334

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/137

### Description

Following the standardisation of JSON modules and CSS modules, HTML modules make use of the import attributes syntax to import HTML. 

```js
import {content} from "foo.html" with { type: "html" };
```

**Comment by annevk** [comment]
Is this proposal being actively developed somewhere? It hasn't been discussed in the Web Components community for many years now.

**Comment by o-t-w** [comment]
It initially stalled because of all the churn with import attributes and because it was decided to [progress CSS modules and JSON modules first](https://github.com/w3ctag/design-reviews/issues/334#issuecomment-529789278). Sadly the Edge team (who originally worked on it) [have not had the bandwidth](https://x.com/dandclark1/status/1488319431230955523?s=20) to progress the specification, but the Web Components Community Group are still keen to see it progress. The [initial issue thread](https://github.com/WICG/webcomponents/issues/645) is still pretty active. Developer sentiment is still positive [1](https://x.com/mhartington/status/1573115906200330244?s=20), [2](https://x.com/brianleroux/status/1550360239018500096?s=20), [3](https://github.com/sveltejs/svelte/issues/3898#:~:text=There%27s%20also%20potential%20for%20further%20benefits%20in%20future%20%E2%80%94%20by%20putting%20markup%20in%20%3Ctemplate%3E%20elements%20that%20are%20on%20the%20page%20(generated%20during%20SSR)%2C%20or%20in%20HTML%20modules%20if%20we%20ever%20get%20those.%20This%20would%20mean%20less%20JavaScript%2C%20and%20we%20can%20take%20advantage%20of%20the%20browser%27s%20parser%20(which%20is%20fast!))

**Comment by jaredcwhite** [comment]
I can concur, still lots of chatter out there in web component circles. I will hear questions to the effect of "why can't we just write an HTML template and import that as a web component?" To which I always reply, well hopefully we will get there with HTML modules!

In fact, I wrote a bundler-level solution for it as this esbuild plugin, which is now being used in production:
https://github.com/whitefusionhq/esbuild-plugin-html-modules

**Comment by justinfagnani** [comment]
@annevk true, it hasn't been discussed directly for a while, and I believe that [@dandclark](https://github.com/dandclark) may be working on other things than web specs, but with import attributes landing and talks about declarative custom elements - which would need a HTML module format to be very useful - I think things could be picked up. Not sure what that means for a standard position issue though.

I'm personally working on a new Rollup plugin / polyfill to allow us to try out various semantics.

**Comment by annevk** [comment]
Appreciate the update. I will close this for now. Once there's a proposal with concrete implementer requirements that can be evaluated we'll be happy to go over it. The WebKit team definitely considers this an area worthy of exploration.
