### ISSUE TITLE
New 'onmove' event handler for the Window object

### ISSUE THREAD

**Issue by javifernandez** [WebKit/standards-positions#289]
### WebKittens

@annevk @smfr

### Title of the spec

window.onmove

### URL to the spec

https://html.spec.whatwg.org/multipage/webappapis.html#event-handlers-on-elements,-document-objects,-and-window-objects

### URL to the spec's repository

https://github.com/whatwg/html

### Explainer URL

https://github.com/Igalia/explainers/blob/main/onmove-event-handler/README.md

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/938

### Description

The main goal of this feature is to provide web authors a mechanism to track and control the position of the Window object.

The feature would probably involve both, the HTML spec and the CSSOM View Module which defines the Window's [attributes exposed](https://drafts.csswg.org/cssom-view/#extensions-to-the-window-interface) to describe its size and position.

There is an ongoing discussion in the [CSS issue 7693](https://github.com/w3c/csswg-drafts/issues/7693) about potential approaches for its implementation and the most appropriated standard venue.

**Comment by smfr** [comment]
In general adding more API around window positions is not something WebKit is very interested in. I think we should trend in the other direction: web content has no business knowing about how I arrange my browser windows. We should discourage authors from using popup windows, and instead direct them to use HTML dialogs and popups.

**Comment by othermaciej** [comment]
I agree with Simon. We should move towards hiding window position entirely, and doing what we can to obscure window size, as there are excessively powerful cross site fingerprinting signals.

**Comment by javifernandez** [comment]
Thank you for the feedback. I understand the concerns about privacy caused by exposing the Window's position to the web content. I think I´d need to reflect more about them in the explainer and try to make the proposal more robust on this regard. 

I admit that the interest on this feature may be low, considering  it goes in the opposite direction to what Safari plans for the Window's position and size attributes. However, I wonder if the given arguments are enough to oppose to the proposal. 

First of all, since the information is already exposed, the even is not making the privacy breach bigger. Since the CSSOM View Module already allows UA to hide information about the screen, the event might be never triggered but it doesn't have any negative impact in terms of performance or privacy. 

On the other hand. for the engines and window systems willing to expose the information, an event based approach has considerable advantages against polling.

**Comment by annevk** [comment]
What we are saying is that the information exposure is a bug to be fixed, not a feature to be celebrated.

**Comment by javifernandez** [comment]
The statement in the Security and Privacy considerations has been merged not so long ago, and the issue has been discussed recently in the CSS WG. As far as I know there are no plans to remove or even deprecate the attributes, so the browser's choice of hiding the information still stands as the best fix to such potential bugs. 

For the browsers willing to, and OSs capable of, updating the CSSOM View attributes a  new event could be seen as a way to warn users and/or web authors about that information exposure and implement features (even privacy related) they want in a more efficient way. In any case, the new event is not making the potential privacy breach bigger.

**Comment by marcoscaceres** [comment]
We can probably glean a position from the feedback above, which seems to be “opposed”.

**Comment by annevk** [comment]
I suggest we mark this as "opposed" one week from now, per the rationale stated above.

**Comment by ecstrema** [comment]
As this has not moved in a while and the current official position is still "opposed", I'd like to add a few comments, some of which have been stated before, but might be worth looking at again:

- `window.onmove` can currently be polyfilled by polling `window.screentop` and `window.screenleft`. 
- These two last properties on window have been there for ages and are not in any path towards deprecation. 
- having `window.onmove` would also be better for performance, which is, from what I gather, one of the main interest of the WebKit team. 

The current main opposing argument is fingerprinting, but the absence of ˋwindow.onmove` has no impact, since it can be polyfilled. 

I hope I'm not missing anything. 

For the use case, I currently use the polling technique as an experimental way to understand the position of dock widgets on a multi-display setup.

**Comment by annevk** [comment]
That polyfill won't work in private browsing mode. It's our ambition to stop it from working everywhere eventually.

**Comment by ecstrema** [comment]
> That polyfill won't work in private browsing mode. It's our ambition to stop it from working everywhere eventually.

This would probably be counterproductive, as the browser being Safari + the polyfill not working would give yet more information about the browser and its version, isn't it? 

Plus, as it doesn't work in private browsing mode, adding `window.onmove`, the security feature is already useful for the people that want it. Meanwhile the people caring about the features can still disable private browsing and get the full performant version. 

I see it this way:

- The performance impact for users is positive. 
- The privacy concerns are already handled by private browsing mode
- adding it doesn't prevent it from being disabled along with `window.screentop`
- in its current form, if I understand correctly, `window.screentop` never fires, which is exactly the same behavior it would have if it is in the end disabled. The browser will simply stop setting the screentop property, and this will stop the event from firing. 

I don't see a single disadvantage to adding it. 

- the amount of code added and to be maintained is negligible
- as stated before, the performance impact is net positive. 
- the privacy will still be respected in private browsing mode in all cases, and this can be expanded to normal browsing mode without this hindering anything.

**Comment by annevk** [comment]
You are mistaken.
