### ISSUE TITLE
CSS Import Once (`@import-once` or similar)

### ISSUE THREAD

**Issue by trusktr** [WebKit/standards-positions#290]
### Title of the spec

import once

### URL to the spec

https://github.com/w3c/csswg-drafts/issues/6130

### URL to the spec's repository

https://github.com/w3c/csswg-drafts

### Issue Tracker URL

https://github.com/w3c/csswg-drafts/issues

### Explainer URL

See first URL

### TAG Design Review URL

...

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/939

### WebKit Bugzilla URL

...

### Description

The link to the proposal should have all the details. But basically a way to write highly-reusable CSS modules. Currently `@import` is too cumbersome and problematic, as described in the issue, and also in this archived WICG thread:

https://discourse.wicg.io/t/importing-css-only-once/1933

**Comment by annevk** [comment]
It seems this is only an idea and not really a flushed out proposal that can be evaluated. Once there's a draft published by the CSS WG we could take a look.
