### ISSUE TITLE
Custom Highlight API

### ISSUE THREAD

**Issue by marcoscaceres** [WebKit/standards-positions#3]
## Request for position on an emerging web specification

**(Please delete inapplicable rows.)**

* WebKittens who can provide input: @megangardner @whsieh

### Information about the spec

* Spec Title: CSS Custom Highlight API Module Level 1
* Spec URL:  https://drafts.csswg.org/css-highlight-api-1/
* GitHub repository: 
* Issue Tracker (if not the repository's issue tracker): 
* Explainer (if not README.md in the repository): 

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/482

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know
On [WebKit-dev](https://lists.webkit.org/pipermail/webkit-dev/2022-June/032303.html),  @dandclark wrote: 

Hi webkit-dev, 

I would like to request WebKit's current position on the CSS Custom Highlight API [1]. Edge and Chrome are planning to ship this soon [2].

Safari implemented an early version of this API in 99 [3], gated behind the Highlight API experimental flag. It looks like it's been updated since then to match changes in the spec, e.g. HighlightRangeGroup has been renamed to Highlight. The remaining major difference between the Safari and Chromium implementation is that the Safari implementation doesn't yet support live Ranges, only StaticRanges. The API is still off-by-default, behind the experimental flag.

Is there anything that can be shared about WebKit's plans to further develop the API and eventually ship it on-by-default?

Thanks,
Dan Clark

[1] https://drafts.csswg.org/css-highlight-api-1/
[2] https://groups.google.com/a/chromium.org/g/blink-dev/c/pxgVrAzMfyk
[3] https://developer.apple.com/safari/technology-preview/release-notes/#r99

**Comment by hober** [comment]
@megangardner @whsieh, thoughts?

**Comment by marcoscaceres** [comment]
Spoke to colleagues internally and we are supportive. @megangardner is also co-editor of that spec. 

Unless anyone objects, we will mark this as "support" in a week or so.

**Comment by hober** [comment]
See also https://github.com/WebKit/standards-positions/issues/95
