### ISSUE TITLE
Cross-Document View Transitions

### ISSUE THREAD

**Issue by bokand** [WebKit/standards-positions#302]
### WebKittens

@nt1m @smfr @hortont424 

### Title of the spec

CSS View Transitions, Level 2

### URL to the spec

https://drafts.csswg.org/css-view-transitions-2/

### URL to the spec's repository

https://github.com/w3c/csswg-drafts

### Explainer URL

https://github.com/WICG/view-transitions/blob/main/cross-doc-explainer.md

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/851

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/677

### Description

This is the level 2 version of the CSS View Transitions API, which adds support for cross-document view transitions.

Webkit's [position issue for CSS View Transitions Level 1 ](https://github.com/WebKit/standards-positions/issues/48)

**Comment by bokand** [comment]
For completeness: this proposal relies on the `pagereveal` event - [Webkit Position Issue](https://github.com/WebKit/standards-positions/issues/303)

**Comment by marcoscaceres** [comment]
@smfr, @hortont424, do you have opinions about this proposal?

**Comment by Ayfri** [comment]
Any update ?

**Comment by bokand** [comment]
FYI: Renamed this to "Cross-Document View Transitions" since L2 version of the spec contains a couple of different concepts in addition to cross-document transitions.

**Comment by ryantownsend** [comment]
This may be a duplicate of https://github.com/WebKit/standards-positions/issues/193 – could be worth closing one / merging?

**Comment by nt1m** [comment]
Duplicate of #193

Thanks!
