### ISSUE TITLE
`pagereveal` event

### ISSUE THREAD

**Issue by bokand** [WebKit/standards-positions#303]
### WebKittens

@nt1m

### Title of the spec

HTML: pagereveal event

### URL to the spec

https://html.spec.whatwg.org/#pagerevealevent

### URL to the spec's repository

https://github.com/whatwg/html/

### Explainer URL

https://github.com/WICG/view-transitions/blob/main/cross-doc-explainer.md#javascript-api

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/851

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/677

### Description

This event is a dependency of the CSS View Transitions Level 2 spec ([Webkit Position Issue](https://github.com/WebKit/standards-positions/issues/302)).

There was significant review and technical debate on https://github.com/whatwg/html/issues/9315 and spec changes were accepted into HTML.

The TAG review and Explainer both point to the larger CSS View Transitions Level 2 items which included this event as part of the design (then called `reveal`).

**Comment by bokand** [comment]
Friendly ping as Chromium is getting ready to send out an intent to ship for this and we'd like to get a signal from WebKit before we do so.

**Comment by bokand** [comment]
FYI: we've sent out an [intent-to-ship](https://groups.google.com/u/2/a/chromium.org/g/blink-dev/c/S67zJ1AYW2U) for this on blink-dev targeting M123.

**Comment by nt1m** [comment]
I'm planning to mark this as supportive in a week if there are no objections. The standard is reasonable, and @mattwoodrow  is implementing it.
