### ISSUE TITLE
Deprecation of prefixed HTMLVideoElement-specific Fullscreen APIs

### ISSUE THREAD

**Issue by tguilbert-google** [WebKit/standards-positions#306]
### Title of the spec

Deprecation of prefixed HTMLVideoElement-specific fullscreen APIs

### URL to the spec

https://fullscreen.spec.whatwg.org/#api

### TAG Design Review URL

N/A

### Mozilla standards-positions issue URL

N/A

### Description

The non-prefixed Fullscreen API has been supported on most browsers for some time now:
https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#browser_compatibility

Chromium has been looking to remove of the following prefixed APIs from the `<video>` tag [since 2014](crbug.com/346236):

- readonly attribute boolean webkitSupportsFullscreen;
- readonly attribute boolean webkitDisplayingFullscreen;
- void webkitEnterFullscreen();
- void webkitExitFullscreen();
- void webkitEnterFullScreen(); // Note the different capitalization of the "S" in FullScreen.
- void webkitExitFullScreen(); // Note the different capitalization of the "S" in FullScreen.

Usage of the APIs have been declining over the past years. Chromium might try to remove the APIs entirely in 2024 ([Link to Blink-dev discussion](https://groups.google.com/a/chromium.org/g/blink-dev/c/jrkCYeUSusg)).

Is WebKit interested in removing these APIs eventually? It seems like support for the non-prefixed APIs is only available on iPads, and not on iOS, according to the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API#api.document.fullscreenelement).

Thank you!

**Comment by hober** [comment]
@jernoble

**Comment by lukewarlow** [comment]
https://developer.apple.com/documentation/safari-release-notes/safari-17_4-release-notes - it's seems the unprefixed APIs are in the next safari release for iOS. Obviously things may change before shipping but it gives an indication.

**Comment by annevk** [comment]
Generally we're interested in removing prefixed APIs where possible. And if not possible, attempt to standardize them.

I'm not really sure how that relates to standards-positions though, unless these are currently standardized which I don't think is the case?

**Comment by tguilbert-google** [comment]
You're right that these do not strictly require a standards-positions. This could have also been a bug on the WebKit bug tracker.

This was opened as part of the blink deprecation process, partly as a heads-up for the removal of these APIs, and partly to inquire about the status of the unprefixed Fullscreen APIs being available for Safari on iOS eventually.

It's nice to know from [the comment above](https://github.com/WebKit/standards-positions/issues/306#issuecomment-1911106462) that the unprefixed APIs are on the roadmap!

This issue could be closed if there is nothing else to add. Thanks!

**Comment by annevk** [comment]
Sounds good, hope it works out!
