### ISSUE TITLE
New attribute to control UA-provided writing assistance

### ISSUE THREAD

**Issue by stephanieyzhang** [WebKit/standards-positions#308]
### WebKittens

@annevk, @marcoscaceres, @hober

### Title of the spec

Add a new attribute called 'writingsuggestions' to control UA-provided writing assistance

### URL to the spec

https://github.com/whatwg/html/pull/10018

### Explainer URL

https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/WritingSuggestions/explainer.md

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/924

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/855

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=266824

### Radar URL

rdar://problem/120279516

### Description

The new attribute 'writingsuggestions' has values true/falsethat would allow developers to turn on/off browser-provided writing suggestions. This attribute will have a default state per element, as established by the UA. The attribute's state for an element can also be inherited from ancestor elements, thereby allowing developers to control this functionality at a per-element or per-document/sub-document scale.

**Comment by marcoscaceres** [comment]
Suggesting we mark this as "support" as a few of us have been collaborating on this feature together with @sanketj and other folks on the WHATWG side. We have indicated we are satisfied with the spec changes/design and the thorough test suite. Looking forward to the PR landing in HTML soon! 

Unless we hear objections or comment to the contrary, we will make the above our position in a week or so.
