### ISSUE TITLE
ReadableStream async iteration

### ISSUE THREAD

**Issue by MattiasBuelens** [WebKit/standards-positions#319]
### WebKittens

@annevk

### Title of the spec

ReadableStream async iteration

### URL to the spec

https://streams.spec.whatwg.org/#rs-asynciterator

### URL to the spec's repository

https://github.com/whatwg/streams

### Explainer URL

https://github.com/whatwg/streams/pull/1306

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=194379

### Radar URL

rdar://problem/96318671

### Description

This change to the Streams standard adds support for the [async iterable protocol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols) to the `ReadableStream` API, enabling readable streams to be used as the source of `for await...of` loops.

Spec change landed in https://github.com/whatwg/streams/pull/980 and https://github.com/whatwg/streams/pull/1035. (Yes, this spec change is already four years old. We forgot to ask for an official position from WebKit back then, so the second best time is now. 😅)

WPT tests are in [streams/readable-streams/async-iterator.any.js](https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/async-iterator.any.js).

Firefox has shipped this in 2023 in version 110 (see [caniuse](https://caniuse.com/mdn-api_readablestream_--asynciterator)), and Chrome is currently implementing this (see [feature on ChromeStatus](https://chromestatus.com/feature/5143121161879552)).

**Comment by annevk** [comment]
I suggest we mark this as "position: support" one week from now, barring any objections. This is pretty much expected behavior for an API like this at this point.
