### ISSUE TITLE
Geolocation Sensor

### ISSUE THREAD

**Issue by marcoscaceres** [WebKit/standards-positions#32]
## Request for position on an emerging web specification

* WebKittens who can provide input: 

### Information about the spec

* Spec Title: Geolocation Sensor
* Spec URL: https://w3c.github.io/geolocation-sensor/
* GitHub repository: https://github.com/w3c/geolocation-sensor/

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/36 (harmful)

### Anything else we need to know

Defines the GeolocationSensor interface for obtaining the geolocation of the hosting device. The spec claims this is a modern incarnation of Geolocation API. The W3C already have a well-maintained and highly interoperable Geolocation spec. Thus, this new specification seems to provide limited value.

**Comment by tomayac** [comment]
@anssiko FYI. Personally, I think it makes sense to put this effort on hold, at least until we make progress on advanced features like background geolocation and geofencing.
