### ISSUE TITLE
View Transition Classes

### ISSUE THREAD

**Issue by vmpstr** [WebKit/standards-positions#321]
### WebKittens

@nt1m

### Title of the spec

View Transitions, Level 2 (view-transition-class)

### URL to the spec

https://drafts.csswg.org/css-view-transitions-2/#view-transition-class-prop

### URL to the spec's repository

https://github.com/w3c/csswg-drafts/

### Explainer URL

https://github.com/vmpstr/web-proposals/blob/main/explainers/view-transition-classes.md

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/938

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/988

### Description

This feature introduces a new CSS property view-transition-class which allows the developer to specify one or more view transition classes. The developer can then select the ViewTransition pseudo elements using these classes (e.g. `::view-transition-group(*.class)`).

This is an extension to the ViewTransition API that simplifies styling of view transition pseudo elements in a similar way that CSS classes simplify styling of regular DOM elements.

**Comment by nt1m** [comment]
This solves repetition in certain use cases of View Transitions in a straightforward way.

I'll mark this as supportive if there are no objections within 7 days.
