### ISSUE TITLE
ContentVisibilityAutoStateChanged event

### ISSUE THREAD

**Issue by vmpstr** [WebKit/standards-positions#33]
### Information about the spec

* Spec Title: CSS Contain: Content Visibility
* Spec URL: This will be an amendment to https://drafts.csswg.org/css-contain-2/
* Issue Tracker (if not the repository's issue tracker): https://github.com/w3c/csswg-drafts/issues
* Explainer (if not README.md in the repository): https://github.com/vmpstr/web-proposals/blob/main/explainers/cv-auto-event.md

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/756
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/664

### Anything else we need to know

CSSWG discussion: https://github.com/w3c/csswg-drafts/issues/7384#issuecomment-1176847043

**Comment by hober** [comment]
The relevant spec text is https://drafts.csswg.org/css-contain-2/#content-visibility-auto-state-change

**Comment by annevk** [comment]
So this event is intentionally not synchronized with rendering updates? Although it does seem like the task queueing should happen from the "update the rendering" algorithm given what appears to trigger it.

cc @smfr @nt1m

**Comment by nt1m** [comment]
@rwlbuis @cathiechen

**Comment by annevk** [comment]
Discussing this with colleagues it seems like this should be "position: support". If anyone disagrees, please say so within a week. Thanks!

**Comment by nt1m** [comment]
This is fine to us, and we actually landed the implementation in WebKit.
