### ISSUE TITLE
Constructors for RTC Encoded Frames with metadata

### ISSUE THREAD

**Issue by guidou** [WebKit/standards-positions#334]
### WebKittens

@youennf

### Title of the spec

Constructors for RTC Encoded Frames with Metadata

### URL to the spec

https://github.com/w3c/webrtc-encoded-transform/pull/223

### Explainer URL

https://github.com/guidou/webrtc-extensions/blob/main/constructor-explainer.md

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/942

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1009

### Description

Add constructors to RTC Encoded Frames that allow specifying custom metadata. This is a relatively small addition to the [WebRTC Encoded Transform spec](https://w3c.github.io/webrtc-encoded-transform/).
The most important use case for this proposal also involves another extension spec called [RTC Encoded Source](https://github.com/w3c/webrtc-extensions/pull/198) which we are discussing in the WebRTC WG and for which a separate position request will be sent soon.

**Comment by Ahmad-S792** [comment]
@youennf

**Comment by marcoscaceres** [comment]
Closing, as @youennf already left comments on the PR. This doesn't require a standards position... just review on pull request.
