### ISSUE TITLE
Importmap integrity

### ISSUE THREAD

**Issue by yoavweiss** [WebKit/standards-positions#335]
### WebKittens

@annevk

### Title of the spec

Importmap integrity

### URL to the spec

https://github.com/whatwg/html/pull/10269

### URL to the spec's repository

https://github.com/whatwg/html

### Explainer URL

https://github.com/guybedford/import-maps-extensions?tab=readme-ov-file#integrity

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1010

### Description

Currently it's impossible to use ES module imports in environments that require subresource integrity for security or privacy reasons. This is a relatively small addition to the platform that would enable it.

**Comment by annevk** [comment]
Colleagues and I find it a good idea to expand the set of resources you can supply integrity metadata for. As such I suggest we resolve this as "position: support" one week from now.
