### ISSUE TITLE
AudioContext.onerror

### ISSUE THREAD

**Issue by gsinafirooz** [WebKit/standards-positions#340]
### WebKittens

I don't know.

### Title of the spec

Web Audio AudioContext.onerror

### URL to the spec

https://github.com/WebAudio/web-audio-api/pull/2580

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/950

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1016

### Description

This feature is the top unimplemented feature per a survey that was conducted recently. Please see https://docs.google.com/presentation/d/1DNjlh_JwjfwDzoULAUx5wUj2Igrx-eUbZ2ZHltLGOZo/preview?slide=id.g9bcfd5e720_0_18.

**Comment by marcoscaceres** [comment]
I think it's better to just add @jernoble as a reviewer for these kinda of pull requests to the spec. 

Let's pick this up in the spec's repo..
