### ISSUE TITLE
Allow converting VideoFrame to RGB pixel formats by calling VideoFrame.copyTo()

### ISSUE THREAD

**Issue by Djuffin** [WebKit/standards-positions#341]
### WebKittens

@youennf

### Title of the spec

WebCodecs

### URL to the spec

https://www.w3.org/TR/webcodecs/#dom-videoframecopytooptions-format

### URL to the spec's repository

https://github.com/w3c/webcodecs

### Explainer URL

https://gist.github.com/Djuffin/9e2f98025ead49998524510cfeed8d33

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/951

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1017

### Description

Converting YUV video frames to RGB is often required for processing them in libraries like TensorFlow.js and OpenCV.js.
Previously the only possible way to achieve this was rendering the frame on a canvas.

Specifying `VideoFrameCopyToOptions.format` and `VideoFrameCopyToOptions.colorSpace` make it possible to *asynchronously* convert frames to RGB pixel format by calling `VideoFrame.copyTo()` without having to use an extra canvas.

**Comment by youennf** [comment]
The use case is fine and the API is better than going through a canvas (more straightforward and async by nature).

**Comment by marcoscaceres** [comment]
This is a draft position. Unless anyone objects within a week we will change it to the official position. 

@Djuffin, we discussed this proposal and we are "supportive" with a concern around the API Design. 

The one thing that would be a nice addition is having some means to synchronously detect if copying to a colorspace would be possible without first needing to call `.copyTo()` (i.e., some kind of support check). We can see it's feasible to, for example, create a `VideoFrame` and perform support checks by seeing if it throws... but, to us, that feels like not so great developer ergonomics. 

Have you thought about adding some kind of mechanism to check what colorspaces the browser supports?

**Comment by Djuffin** [comment]
[VideoFrame.allocationSize()](https://www.w3.org/TR/webcodecs/#dom-videoframe-allocationsize) is synchronous and it throws if conversion is not supported.

**Comment by marcoscaceres** [comment]
Note that WebIDL will drop dictionary member on the floor, so VideoFrame.canCopyTo() can't rely on dictionary (it could take an `object` though, and then iterate over the member names that way to reject on any unknown member name... and then check the details of each that is supported.)

**Comment by marcoscaceres** [comment]
Closing with "support" position. Please ping us on the W3C side when there's a PR for us to review!
