### ISSUE TITLE
Support Skip-Ad media session action

### ISSUE THREAD

**Issue by jiajiabingcheng** [WebKit/standards-positions#350]
### WebKittens

 @youennf, @jernoble 

### Title of the spec

Support Skip-Ad media session action

### URL to the spec

https://www.w3.org/TR/mediasession/#dom-mediasessionaction-skipad

### URL to the spec's repository

https://github.com/w3c/mediasession

### Explainer URL

https://developer.chrome.com/blog/media-updates-in-chrome-73#skipad
https://github.com/w3c/mediasession/pull/203#issuecomment-432529816 

### TAG Design Review URL

 https://github.com/w3ctag/design-reviews/issues/957

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1026

### Description

This feature was initially proposed and implemented four years ago but remained disabled due to a lack of practical use cases. It already received LGTM from the Blink dev group back in February 2019. Given our team's plan to implement a feature related to this action, we are now proposing to enable it.

**Comment by beaufortfrancois** [comment]
cc @youennf

**Comment by beaufortfrancois** [comment]
FYI https://github.com/w3c/mediasession/pull/203#issuecomment-432529816

**Comment by marcoscaceres** [comment]
I wonder if it might be more effective to rip this out of the spec, and then send it as PR for us to discuss in the Media WG? 

If the feature didn't have implementer consensus, then it probably shouldn't have been added to the spec in the first place, right?

**Comment by jyasskin** [comment]
https://caniuse.com/?search=skipad says this shipped in Safari 15.
