### ISSUE TITLE
WebAuthn hints parameter

### ISSUE THREAD

**Issue by agl** [WebKit/standards-positions#365]
### WebKittens

@pascoej 

### Title of the spec

Web Authentication

### URL to the spec

https://w3c.github.io/webauthn/#enum-hints

### URL to the spec's repository

https://github.com/w3c/webauthn

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1043

### Description

p.s. just asking about the [`hints` parameter](https://w3c.github.io/webauthn/#enum-hints) in WebAuthn, not the whole spec. Chromium wishes to ship it.

**Comment by marcoscaceres** [comment]
As this is already in the spec, presumedly it has working group consensus. Therefore closing this issue. 

@agl, have you filed a webkit bug for this?
