### ISSUE TITLE
SVG favicons

### ISSUE THREAD

**Issue by nileshprajapati** [WebKit/standards-positions#367]
### Title of the spec

SVG favicons

### URL to the spec

https://html.spec.whatwg.org/multipage/links.html#rel-icon

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=136059

### Radar URL

rdar://5697363

### Description

https://caniuse.com/?search=svg%20favicon

Browsers:
Chrome/Edge: Support
Firefox: Support

**Comment by annevk** [comment]
I suggest resolving this as "position: support" one week from now.

While it's not entirely clear to me that standards-positions is a good place to capture this, as formats are not directly covered by the standard, there's also not another place that would be more suitable so we might as well address our stance here.

**Comment by nileshprajapati** [comment]
Hi, @annevk Shall we give this more time to others to comment or resolve it as "position: support"?
