### ISSUE TITLE
CSS Nesting: The Nested Declarations Rule

### ISSUE THREAD

**Issue by andruud** [WebKit/standards-positions#369]
### WebKittens

@mdubet @fantasai

### Title of the spec

CSS Nesting 

### URL to the spec

https://drafts.csswg.org/css-nesting-1/#nested-declarations-rule

### URL to the spec's repository

https://github.com/w3c/csswg-drafts/tree/main/css-nesting-1

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1048

### Description

See also:

 - The spec for the rule itself: https://drafts.csswg.org/css-nesting-1/#the-cssnestrule
 - The new behavior for insertRule (step 4): https://drafts.csswg.org/cssom/#insert-a-css-rule
 - Previous position for `@nest`: https://github.com/WebKit/standards-positions/issues/337

**Comment by annevk** [comment]
@mdubet as per https://github.com/WebKit/standards-positions?tab=readme-ov-file#resolving-an-issue-with-a-position you really ought to leave a comment and give some time for further feedback. But given it's been many months at this point I suppose we can consider this done.
