### ISSUE TITLE
WebAuthn JSON serialization

### ISSUE THREAD

**Issue by kreichgauer** [WebKit/standards-positions#373]
### WebKittens

@pascoej

### Title of the spec

Web Authentication: JSON serialization

### URL to the spec

https://w3c.github.io/webauthn/#ref-for-dom-publickeycredential-tojson

### URL to the spec's repository

https://github.com/w3c/webauthn

### Explainer URL

https://github.com/w3c/webauthn/wiki/Explainer:-JSON-Serialization-Methods

### Mozilla standards-positions issue URL

(shipped)

### Description

Only inquiring about the [PublicKeyCredential.parseCreationOptionsFromJSON()](https://w3c.github.io/webauthn/#sctn-parseCreationOptionsFromJSON), [PublicKeyCredential.parseRequestOptionsFromJSON()](https://w3c.github.io/webauthn/#sctn-parseRequestOptionsFromJSON) and [PublicKeyCredential.toJSON()](https://w3c.github.io/webauthn/#dom-publickeycredential-tojson) methods.

Firefox has already shipped these. Chrome is planning to ship: https://chromestatus.com/feature/5141695044255744?gate=6322764007342080

**Comment by marcoscaceres** [comment]
I don't think this needs a standards position... it's already in the spec, which theoretically means there was consensus in the working group.

**Comment by lgarron** [comment]
> I don't think this needs a standards position... it's already in the spec, which theoretically means there was consensus in the working group.

@marcoscaceres Do you know if we can expect a Safari implementation any time soon? Safari is now the only browser without support for this, but I can't find any information about implementation here or on Bugzilla.

The canonical polyfill (https://github.com/github/webauthn-json) is tricky to update to keep in sync with the spec, and the ecosystem will greatly benefit when sites can depend on browser support.

**Comment by lgarron** [comment]
> @lgarron it has been added to WebKit, but hasn't made it to Safari yet.
> 
> [WebKit/WebKit#34401](https://github.com/WebKit/WebKit/pull/34401)

yiss, that's what I was trying to find! 🤩

Glad to see it, thanks!
