### ISSUE TITLE
Support for PointerEvent getCoalescedEvents() API

### ISSUE THREAD

**Issue by mustaqahmed** [WebKit/standards-positions#374]
### WebKittens

@gsnedders @marcoscaceres

### Title of the spec

Pointer Events level 3: Coalesced events

### URL to the spec

https://w3c.github.io/pointerevents/#coalesced-events

### URL to the spec's repository

https://github.com/w3c/pointerevents

### Description

For performance reasons, user agents may choose not to send all `pointermove` events to the main thread.  This optimization reduces the granularity and fidelity of pointer movements from the JavaScript's perspective, particularly for fast and large movements.  `PointerEvent.getCoalescedEvents()` exposes the "held-back" events to the JavaScript as a list within a single `pointermove` event.

**Comment by Ahmad-S792** [comment]
@rr-codes & @aprotyas

**Comment by nt1m** [comment]
We've started implementing this and we don't currently have any concerns. I'll mark this as support in a week pending objections.
