### ISSUE TITLE
CSS Shape function

### ISSUE THREAD

**Issue by smfr** [WebKit/standards-positions#377]
### Title of the spec

CSS Shapes Module Level 2

### URL to the spec

https://drafts.csswg.org/css-shapes-2/

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=238371

### Radar URL

rdar://problem/90919476

### Description

The `shape()` function allows the author to describe a path (akin to an SVG path) for use in `clip-path` and other properties that take Basic Shapes, in a way where the path points are described using CSS units, which allows the paths to be responsive.

This is essential to allowing clip-path to adjust to the size of the box, for example.

**Comment by marcoscaceres** [comment]
@smfr, same as the other CSS one you filed... do we "support" this? Is it implemented?

**Comment by smfr** [comment]
We support this. It's implemented, pending some syntax changes tracked in GitHub Issues.
