### ISSUE TITLE
CSS background-clip: border-area

### ISSUE THREAD

**Issue by smfr** [WebKit/standards-positions#379]
### Title of the spec

CSS background-clip: border-area

### URL to the spec

http://drafts.csswg.org/css-backgrounds-4/

### URL to the spec's repository

https://github.com/w3c/csswg-drafts

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=277693

### Radar URL

rdar://131761899

### Description

The proposal at https://github.com/w3c/csswg-drafts/issues/9456 allows authors to fill the border area with the background.

**Comment by marcoscaceres** [comment]
@smfr, do we "support" this?

**Comment by smfr** [comment]
We do. Implementation is almost complete.
