### ISSUE TITLE
Multiple Import Maps

### ISSUE THREAD

**Issue by yoavweiss** [WebKit/standards-positions#381]
### WebKittens

@annevk

### Title of the spec

Dynamic import maps

### URL to the spec

https://github.com/whatwg/html/pull/10528

### URL to the spec's repository

https://github.com/whatwg/html

### Explainer URL

https://github.com/whatwg/html/pull/10528#issue-2437162429

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/980

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1058

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=279025

### Radar URL

rdar://135555516

### Description

Import maps currently have to load before any ES module and there can only be a single import map per document. That makes them fragile and potentially slow to use in real-life scenarios: Any module that loads before them breaks the entire app, and in apps with many modules the become a large blocking resource, as the entire map for all possible modules needs to load first.

This proposal is to enable multiple import maps per document, by merging them in a consistent and deterministic way.

**Comment by marcoscaceres** [comment]
@cdumez, who might be good to look at this?

**Comment by yoavweiss** [comment]
Friendly ping! :)
