### ISSUE TITLE
CSS query container flat tree lookup

### ISSUE THREAD

**Issue by lilles** [WebKit/standards-positions#382]
### WebKittens

@anttijk

### Title of the spec

CSS query container flat tree lookup

### URL to the spec

https://drafts.csswg.org/css-conditional-5/

### Description

There was a recent [change](https://github.com/w3c/csswg-drafts/pull/10701) to the specification for container queries in css-conditional-5 to look up the flat tree instead of shadow-including ancestors for query container candidates.

This matches the behavior that Gecko shipped.

Chromium wants to change the implementation to match the new spec.

**Comment by anttijk** [comment]
Sounds sensible.

**Comment by marcoscaceres** [comment]
As there's been no objections since last week, going ahead and closing this.
