### ISSUE TITLE
Import Maps

### ISSUE THREAD

**Issue by bennypowers** [WebKit/standards-positions#39]
### Information about the spec

* Spec Title: Import Maps
* Spec URL: https://wicg.github.io/import-maps/
* GitHub repository: https://github.com/WICG/import-maps

### Design reviews and vendor positions

* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/pull/454

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=220823
* Radar: rdar://problem/73478498

### Anything else we need to know

Import maps unlock much value in using javascript modules, allowing developers to use "bare specifiers", aliasing modules to versioned urls, etc.

**Comment by gsnedders** [comment]
See also https://github.com/whatwg/html/pull/8075 for merging it into HTML.

**Comment by Constellation** [comment]
Now, we are implementing it in https://github.com/WebKit/WebKit/pull/4675

**Comment by annevk** [comment]
Given that we're actively prototyping and helping out with standardization I would suggest we add the "position: support" label one week from today. (In fact, we went beyond what was asked for: https://github.com/whatwg/html/issues/8355.)

**Comment by hober** [comment]
Closing as we've identified our position.
