### ISSUE TITLE
WebXR Hand Input Module - Level 1

### ISSUE THREAD

**Issue by alcooper91** [WebKit/standards-positions#395]
### WebKittens

@AdaRoseCannon

### Title of the proposal

WebXR Hand Input Module - Level 1

### URL to the spec

https://immersive-web.github.io/webxr-hand-input/

### URL to the spec's repository

https://github.com/immersive-web/webxr-hand-input/

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/568

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1070

### Description

This is already shipped in Safari on the Apple Vision Pro to my understanding (https://webkit.org/blog/15443/news-from-wwdc24-webkit-in-safari-18-beta/), but I didn't see a formal citeable positon anywhere.

**Comment by AdaRoseCannon** [comment]
I intend to say that we feel positively about this API.
