### ISSUE TITLE
WebAssembly Relaxed SIMD

### ISSUE THREAD

**Issue by marcoscaceres** [WebKit/standards-positions#4]
## Request for position on an emerging web specification

**(Please delete inapplicable rows.)**

* WebKittens who can provide input: 

### Information about the spec

* Spec Title: 
* Spec URL: https://github.com/WebAssembly/relaxed-simd/tree/main/document/core
* GitHub repository: 
* Issue Tracker (if not the repository's issue tracker): 
* Explainer (if not README.md in the repository): 

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: 

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

On [WebKit-dev](https://lists.webkit.org/pipermail/webkit-dev/2022-June/032304.html), @dtig wrote:  

Hi webkit-dev,

The WebAssembly Relaxed SIMD proposal introduces new vector operations that
take advantage of widely available instruction sets to accelerate compute
workloads. The proposal relaxes the strict portability constraints of
the fixed-width
[SIMD proposal](https://github.com/WebAssembly/simd/tree/master/proposals/simd). We're
hoping to ship this in Chrome 105/106 contingent on a [Phase 4](https://github.com/WebAssembly/proposals#phase-4---standardize-the-feature-wg)
(currently at Phase 3) vote in the Wasm CG, requesting a WebKit position for the proposal.

Proposal: https://github.com/WebAssembly/relaxed-simd
Spec: https://github.com/WebAssembly/relaxed-simd/tree/main/document/core
Implementation status (V8, SpiderMonkey):
https://github.com/WebAssembly/relaxed-simd/blob/main/proposals/relaxed-simd/ImplementationStatus.md
Preliminary performance data that motivated the proposal:
https://github.com/WebAssembly/simd/pull/79

Thanks,
Deepti

**Comment by justinmichaud** [comment]
The WebKittens are neutral. The performance looks exciting, and the operations seem pretty reasonable. We are still worried about the burden this places on developers to test against multiple CPUs, and potential compatibility issues that would result from that.

Thanks again for reaching out!

**Comment by hober** [comment]
Closing as we've identified our position.
