### ISSUE TITLE
Web Authentication's PublicKeyCredential signal* methods

### ISSUE THREAD

**Issue by nsatragno** [WebKit/standards-positions#400]
### WebKittens

@rmondello @pascoej 

### Title of the proposal

PublicKeyCredential signal methods

### URL to the spec

https://w3c.github.io/webauthn/#sctn-signal-methods

### URL to the spec's repository

https://github.com/w3c/webauthn/

### Explainer URL

https://github.com/w3c/webauthn/wiki/Explainer:-WebAuthn-Signal-API-explainer

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/996

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1075

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=278339

### Radar URL

rdar://134285651

### Description

The WebAuthn signal methods allow relying parties to keep WebAuthn authenticator credential state in sync with their view of those credentials. Relying parties can signal that a user's name or display name have been updated, or that a credential is no longer accepted.

**Comment by pascoej** [comment]
Hi Nina. After conferring with colleagues, I would like to report we are "supportive" at this time.

**Comment by annevk** [comment]
@pascoej as per https://github.com/WebKit/standards-positions?tab=readme-ov-file#resolving-an-issue-with-a-position we should give people a week before adding the label, but given it's been a month without comment I think we can consider this done.
