### ISSUE TITLE
CSS Scoping :has-slotted pseudo

### ISSUE THREAD

**Issue by keithamus** [WebKit/standards-positions#404]
### WebKittens

@fantasai, @nt1m, @rniwa, @anttijk 

### Title of the proposal

CSS Scoping :has-slotted pseudo

### URL to the spec

https://drafts.csswg.org/css-scoping/#the-has-slotted-pseudo

### URL to the spec's repository

https://github.com/w3c/csswg-drafts

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1079

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=280608

### Description

Hope to provide an implementation PR this week.

**Comment by rniwa** [comment]
This seems like a decent idea. I suggest we add "position: support" one week from now.
