### ISSUE TITLE
Generate CSS `view-transition-name` from element

### ISSUE THREAD

**Issue by noamr** [WebKit/standards-positions#408]
### WebKittens

@nt1m @fantasai

### Title of the proposal

Generate CSS `view-transition-name` from element

### URL to the spec

https://drafts.csswg.org/css-view-transitions-2/#auto-vt-name

### URL to the spec's repository

https://github.com/w3c/csswg-drafts

### Issue Tracker URL

https://github.com/w3c/csswg-drafts

### Explainer URL

https://github.com/WICG/view-transitions/blob/main/auto-name-explainer.md#self-review-questionnaire-security-and-privacy

### TAG Design Review URL

https://github.com/w3ctag/design-reviews/issues/1001

### Description

We've built this feature in the CSSWG together with Apple folks (@nt1m, @jensimmons, @fantasai), so we hope you guys are still behind it!

**Comment by nt1m** [comment]
We'll mark this as positive in a week pending objections :)
