### ISSUE TITLE
:open pseudo-class

### ISSUE THREAD

**Issue by josepharhar** [WebKit/standards-positions#413]
### WebKittens

@annevk @nt1m

### Title of the proposal

CSS :open pseudo-class

### URL to the spec

https://drafts.csswg.org/selectors-4/#open-state

### URL to the spec's repository

https://drafts.csswg.org

### WebKit Bugzilla URL

https://bugs.webkit.org/show_bug.cgi?id=280637

### Description

There is a corresponding HTML spec PR here: https://github.com/whatwg/html/pull/10126

**Comment by annevk** [comment]
Overall this seems reasonable and thanks for working on it! However, during review it was suggested that we might not need `:closed` as it's redundant with `:not(:open)` and inconsistent with `:popover-open`. It would be good to go over that concern with the CSS WG.
