### ISSUE TITLE
dispatch toggleevents for dialog open/close

### ISSUE THREAD

**Issue by keithamus** [WebKit/standards-positions#418]
### WebKittens

@annevk @rniwa @nt1m 

### Title of the proposal

Dispatch toggle events for the dialog element

### URL to the spec

https://github.com/whatwg/html/pull/10091

### URL to the spec's repository

https://github.com/whatwg/html

### Mozilla standards-positions issue URL

https://github.com/mozilla/standards-positions/issues/1101

### Description

Gecko is shipping this in nightly, Chrome is shipping flagged, but I will be submitting an I2S very shortly.

**Comment by nt1m** [comment]
I'll mark this as supportive in a week pending objections.
