### ISSUE TITLE
TLS Encrypted Client Hello

### ISSUE THREAD

**Issue by davidben** [WebKit/standards-positions#46]
## Request for position on an emerging web specification

* WebKittens who can provide input: networking and TLS folks

### Information about the spec

* Spec Title: TLS Encrypted Client Hello
* Spec URL: https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni
* GitHub repository: https://github.com/tlswg/draft-ietf-tls-esni

### Anything else we need to know

Brief summary of the issue or the subject of the spec.

ECH is a mechanism for encrypting the TLS ClientHello (which includes, among other things, the destination hostname) under a server public key.

**Comment by mcatanzaro** [comment]
WebKit should signal support for this spec IMO. afaik only oppressive nation states are opposed.

That said, an implementation note: this is actually much lower level than WebKit, not something likely to require changes in WebKit itself. WebKit has three network backends: (a) CoreFoundation, used on Apple platforms, which is proprietary, (b) libsoup, which allows arbitrary network backends, but is usually glib-networking (which I maintain) using [GnuTLS](https://gitlab.com/gnutls/gnutls/-/issues/595), or sometimes [OpenSSL](https://github.com/openssl/openssl/issues/7482), and (c) libcurl, which has a dozen different choices for network backend, but is most likely to be OpenSSL. So not only is it platform-specific, each platform involves a bunch of layers, of which WebKit is only the highest. Most likely, for most platforms, WebKit won't need any modifications at all to make ECH work once the lower layers support it.

**Comment by ekinnear** [comment]
I suggest we label this as `position: support` 7 days from now with the following:

> While this isn’t functionality implemented in WebKit itself, but rather something provided by the network stack below WebKit, we are supportive of this work as a mechanism to reduce private information exposure for internet users.

**Comment by gsnedders** [comment]
total nitpick, but maybe "a network stack" or "the network stacks" to make it clear there isn't a singular network stack? (mostly bothering to say this for the sake of precedent when this comes up again!)

**Comment by ekinnear** [comment]
Makes sense, thanks -- edited

**Comment by hober** [comment]
Closing as we've identified our position.

**Comment by Cat-Ling** [comment]
Almost three years and still no support. I can guess a few reasons.
