### ISSUE TITLE
Form-associated custom elements

### ISSUE THREAD

**Issue by calebdwilliams** [WebKit/standards-positions#47]
## Request for position on form-associated custom elements

* WebKittens who can provide input: 
* @rniwa 
* @annevk 

### Information about the spec

* Spec Title: Form-associated custom elements
* Spec URL: https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-face-example
* GitHub repository: https://github.com/whatwg/html/issues

### Design reviews and vendor positions

* Chromium and Mozilla have full implementation

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=197963

### Anything else we need to know

APIs using for allowing custom elements to participate in form submission and constraint validation. Chromium and Mozilla have shipped this feature and [WebKit has begun implementing `ElementInternals`](https://github.com/WebKit/WebKit/pull/2690); however, WebKit's implementation currently lacks the form-associated APIs.

**Comment by rniwa** [comment]
This is under development.

**Comment by bennypowers** [comment]
I believe I found a bug in both [chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1370956) and [firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1793559)' implementations, namely that a [FACE in a fieldset should have it's `formDisabledCallback` called when `disabled` attr is removed from the fieldset](https://bennypowers.dev/face-disabled-repro.html) so please bear that in mind when working on the webkit implementation.

**Comment by othermaciej** [comment]
Does anyone happen to know who originally proposed form-associate custom elements (so I can give due credit with a `from:` label)?

**Comment by annevk** [comment]
(Added in https://github.com/whatwg/html/pull/4383 by tkent from Google referencing https://github.com/WICG/webcomponents/issues/187 by Hayato Ito (also Google) which was a continuation of https://www.w3.org/Bugs/Public/show_bug.cgi?id=24603 filed by Erik Arvidsson in 2014 (strongly suspect still at Google back then).)

**Comment by hober** [comment]
Closing as we've identified our position.
