### ISSUE TITLE
View Transitions API Level 1

### ISSUE THREAD

**Issue by khushalsagar** [WebKit/standards-positions#48]
### Information about the spec

* Spec Title: CSS Shared Element Transitions
* Spec URL: https://drafts.csswg.org/css-shared-element-transitions-1/
* GitHub repository: https://github.com/WICG/shared-element-transitions
* Issue Tracker (if not the repository's issue tracker): 
* Explainer (if not README.md in the repository): https://github.com/WICG/shared-element-transitions/blob/main/explainer.md

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/748
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/677

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

The spec still has some open issues but the overall feature design is concrete at this point. Also [here](https://chromestatus.com/feature/5193009714954240) is the chrome status entry.

**Comment by khushalsagar** [comment]
Heads up, we'll have a session on this feature at TPAC on Wednesday. I'll post the exact time next week. Looking forward to see folks interested there!

**Comment by khushalsagar** [comment]
The breakout session is on September 14 at 3 PST. Details are [here](https://www.w3.org/events/meetings/68a3ec0e-715b-4415-ac23-0d41fa569ea8) including a link to join virtually.

**Comment by fwebdev** [comment]
Any results from the TPAC Session on this Topic?

**Comment by astearns** [comment]
@fwebdev https://www.w3.org/2022/09/14-pagetransitions-minutes.html

**Comment by gugadev** [comment]
Is there some update about the WebKit’s position on this?

**Comment by smfr** [comment]
WebKit supports this proposal.

**Comment by rik** [comment]
Can someone with the permission to update the issue rename the specification in the original post to use "View Transitions"? This will help search for it on https://webkit.org/standards-positions/

**Comment by lukewarlow** [comment]
I don't think the title is the issue I think it's just not showing up at all. Summary.json probably needs syncing?

**Comment by annevk** [comment]
Thanks for noticing that @rik. I fixed it.

**Comment by bokand** [comment]
FYI: In Chromium we're planning to split out some of the pieces of cross-document view transitions to ship separately where it makes sense. Specifically we're currently looking at the `pagereveal` event.

I want to confirm if WebKit is ok with us using the overall signal for view transitions as the position for those pieces? Maybe a bigger question: should we file a new position request for cross-document view transitions as a whole (i.e. view-transitions API level 2) or is this position sufficient (FWIW [Mozilla's reusing the same position for both](https://github.com/mozilla/standards-positions/issues/677#issuecomment-1567988287) but thought I'd ask) @nt1m @smfr

**Comment by nt1m** [comment]
It would be good to file new positions for these.
