### ISSUE TITLE
AV1 video format

### ISSUE THREAD

**Issue by o-t-w** [WebKit/standards-positions#55]
## Request for position on an emerging web specification

**(Please delete inapplicable rows.)**

* WebKittens who can provide input: @jernoble @jyavenard @eric-carlson 

### Information about the spec

* Spec Title: AV1 Bitstream & Decoding Process Specification
* Spec URL: https://aomedia.org/av1/specification/
* GitHub repository: https://github.com/AOMediaCodec/av1-spec
* Explainer (if not README.md in the repository): n/a

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: 

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

Brief summary of the issue or the subject of the spec.

**Comment by voxpelli** [comment]
Related: https://www.reddit.com/r/AV1/comments/vn9nep/avif_finally_coming_to_safari_with_ios_16_and/

I think WebKit actually already supports AV1, but that Safari instead uses whatever video and image that the OS support, but that the next OS that's released stable very soon will support it also in Safari.

**Comment by o-t-w** [comment]
According to caniuse Safari does not support it even in 16 or technology preview https://caniuse.com/av1

**Comment by gsnedders** [comment]
> Related: https://www.reddit.com/r/AV1/comments/vn9nep/avif_finally_coming_to_safari_with_ios_16_and/
> 
> I think WebKit actually already supports AV1, but that Safari instead uses whatever video and image that the OS support, but that the next OS that's released stable very soon will support it also in Safari.

WebKit broadly has no notion of media format support; it's all behind per-port code. Some ports, including those which use gstreamer, do support AV1, but others—including the Apple ports—do not. Apple hasn't made any announcement about AV1 support, though AVIF is supported in Safari 16.

And yes, the Apple ports entirely use OS frameworks for media support; as such, any support for AV1 likely depends on system-level support, and we can't comment about what other teams at Apple are or are not intending to do in future.

**Comment by gsnedders** [comment]
Let's keep this open until we figure out what to do with issues such as this where the position depends on per-port behaviour.

**Comment by othermaciej** [comment]
AV1 for many WebKit ports would likely be provided by the platform, below the WebKit layer. That said, I think most ports are in general positive on this technology. We have other issues in this repo that relate to web and internet standards that are generally implemented by the platform below WebKit, so I think this is ok.

**Comment by hober** [comment]
Closing as we've identified our position.
