### ISSUE TITLE
Request for review on BFCache guides

### ISSUE THREAD

**Issue by rakina** [WebKit/standards-positions#58]
## Request for review on BFCache guides

* WebKittens who can provide input: @annevk @cdumez @hober @marcoscaceres 

Chrome's BFCache team have been working on making sure future web platform APIs will support BFCache by default, which includes adding some BFCache-specific guidelines to [W3C's Design Principles](https://w3ctag.github.io/design-principles/#support-non-fully-active) and [Security & Privacy Questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/#non-fully-active) docs last year. We are now currently in the process of improving the docs and actually factoring out the BFCache guidelines into its own doc (more context [here](https://github.com/w3ctag/design-reviews/issues/628#issuecomment-1227165134)), and we realized recently that we didn't actually get reviews from other browsers last time (it was reviewed only by TAG), so we'd like to formally ask for WebKit's review for these docs:

- Security & Privacy Questionnaire: [HTML version](https://rakina.github.io/security-questionnaire/#bfcache), [Google Docs version](https://docs.google.com/document/d/1jE7qIBrctm778nUyzHAlrs-v8TK90vJnXSxgw0rx8Dw/edit#heading=h.y3vaaqr2n1hj), [PR](https://github.com/w3ctag/security-questionnaire/pull/144)
- Design Principles: [HTML version](https://rakina.github.io/design-principles/#support-non-fully-active), [Google Docs version](https://docs.google.com/document/d/1jE7qIBrctm778nUyzHAlrs-v8TK90vJnXSxgw0rx8Dw/edit#heading=h.u8nqs4k0yd5i), [PR](https://github.com/w3ctag/design-principles/pull/392)
- New "Supporting BFCached Documents" doc: [HTML version](https://rakina.github.io/bfcache-guide/), [Google Docs version](https://docs.google.com/document/d/1jE7qIBrctm778nUyzHAlrs-v8TK90vJnXSxgw0rx8Dw/edit#heading=h.6grduywchojv).

Thanks a lot :)

**Comment by marcoscaceres** [comment]
Thanks @rakina! I had a look at the three documents above and all look/read great. I think everyone is generally supportive of bringing more awareness to specification editors about the implications of the BFCache, and how they might impact various APIs/features. In particular, it’s great to have consistent guidance about what to do when a document is in a cached state. It’s also good to see guidance for developers around the use of “pageshow” “pagehide” events, and that APIs should just do the right thing on behalf of developers when possible.

I'm not sure we need to take a "webkit position" here, but I think the aforementioned folks above would be happy to provide input to the documents you listed if they undergo further changes. Just ping us as needed. Have you found a home at the W3C the for "Supporting BFCached Documents" document?

**Comment by othermaciej** [comment]
`concerns: venue`: the document is proposed for TAG review but seems to currently exist in a personal repo (and Google Docs).

It seems like a good next step is to submit the BFCache guide to the TAG for review.

Also, a minor nit: it might be clearer to call this a "Back/Forward Cache Guide" rather than a "BFCache Guide". "BFCache" (with that capitalization) seems to be a Chromium term, or at best browser developer jargon, and not a standards term.

**Comment by rakina** [comment]
Thanks for reviewing! We are currently [waiting to get TAG's reply](https://github.com/w3ctag/design-principles/pull/392#issuecomment-1269258163) on where to host the new guide for review, I'll update this thread when we get a response. I've also updated the title of the doc to use the full "Back/Forward Cache" but kept most of the text to use the shorter BFCache to keep it short, hope that's ok. If everything looks OK from WebKit's side, is it possible to get the LGTM for the existing PRs?

Also, please let us know if WebKit has a different approach for how features behave with BFCache, in case that doesn't align with what we have in the guide right now. (Since I think there are some Chromium vs WebKit BFCache behavior differences that we noticed, e.g. network requests are immediately dropped when a page is bfcached)

**Comment by annevk** [comment]
FWIW, I left a number of comments on https://github.com/w3ctag/bfcache-guide/pull/1 but they ended up being ignored.

**Comment by rakina** [comment]
Hi @annevk, I'm so sorry that the PR got merged with some unresolved issues still. I was also surprised it got merged so suddenly (I didn't ask for TAG to do that). I'm also sorry for not being able to respond to your comments there quickly, mostly due to my poor scheduling and waiting to get some other input from other people internally. I will make sure I resolve your remaining concerns, and have filed issues for them at https://github.com/w3ctag/bfcache-guide/issues/2 and https://github.com/whatwg/html/issues/8872. We also welcome further suggestions and comments either here or as separate GitHub issues, or in any form really.

Thanks again for taking the time and effort to review the guide thoroughly and other BFCache stuff in general (along with other WebKit folks), I (and the Chromium BFCache team) really appreciate it a lot!

**Comment by hober** [comment]
Marking done as Anne left a number of comments on the text.
