### ISSUE TITLE
DisplayMediaStreamConstraints.surfaceSwitching

### ISSUE THREAD

**Issue by marcoscaceres** [WebKit/standards-positions#6]
## Request for position on an emerging web specification

**(Please delete inapplicable rows.)**

* WebKittens who can provide input: @youennf, @jernoble, @eric-carlson

### Information about the spec

* Spec Title: Introduce DisplayMediaStreamConstraints.surfaceSwitching
* Spec URL: https://github.com/w3c/mediacapture-screen-share/pull/225/ (merged)
* GitHub repository: 
* Issue Tracker (if not the repository's issue tracker): 
* Explainer (if not README.md in the repository): https://docs.google.com/document/d/1kqdLoUcwWe8znVCMXyz2FHk9WMylHbIo7gUjhyHmY_w/edit?usp=sharing

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/653

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

On [WebKit dev](https://lists.webkit.org/pipermail/webkit-dev/2022-June/032305.html), @eladalon1983 wrote: 

This is a request for WebKit's position on extending getDisplayMedia to
also accept DisplayMediaStreamConstraints.surfaceSwitching.
The PR that introduced this behavior to the getDisplayMedia spec was
approved by Apple engineer Youenn Fablet.

Links:
* ChromeStatus entry: https://chromestatus.com/feature/5067650299330560

**Comment by hober** [comment]
@jernoble @eric-carlson, thoughts?

**Comment by youennf** [comment]
This API is exposing a preference so that UAs can finetune their own UI, if they want to.
The fact a UA implements it or not should not cause web compatibilities. In that sense, this is not too controversial.

This preference seems mostly targeted to a particular User Agent (Chrome) UI and I do not think it is something we can leverage in existing macOS UI.
I do not anticipate WebKit implementing it, at least in a foreseeing future.

**Comment by eladalon1983** [comment]
> This preference seems mostly targeted to a particular User Agent (Chrome) UI and I do not think it is something we can leverage in existing macOS UI.

Hasn't Apple only recently shipped the feature of letting users switch which screen or window they share?

**Comment by youennf** [comment]
> Hasn't Apple only recently shipped the feature of letting users switch which screen or window they share?

Right, there is OS level UI to enable users to dynamically switch.
The point is about the appetite to allow web pages to disable this OS level UI.

**Comment by othermaciej** [comment]
> This API is exposing a preference so that UAs can finetune their own UI, if they want to. The fact a UA implements it or not should not cause web compatibilities. In that sense, this is not too controversial.
> 
> This preference seems mostly targeted to a particular User Agent (Chrome) UI and I do not think it is something we can leverage in existing macOS UI. I do not anticipate WebKit implementing it, at least in a foreseeing future.

Would it be valuable to implement at least to the level of silently ignore it?
