### ISSUE TITLE
URLPattern API

### ISSUE THREAD

**Issue by brentfulgham** [WebKit/standards-positions#61]
## Request for position on an emerging web specification

* WebKittens who can provide input: @achristensen07,  @MenloDorian, @rniwa, @annevk 

### Information about the spec

* Spec Title: URLPattern API
* Spec URL: https://urlpattern.spec.whatwg.org/
* GitHub repository: https://github.com/whatwg/urlpattern
* Explainer: https://github.com/whatwg/urlpattern/blob/main/explainer.md#urlpattern

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/566

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

This proposal creates a native web API to match URLs called URLPattern. URLPattern would support both web developer use in JS and native URL matching in other web APIs. For example, the initial use cases discuss using URLPattern for service worker scope matching.

**Comment by karlcow** [comment]
* [Mozilla Standard Position](https://github.com/mozilla/standards-positions/issues/566). Latest discussions were one year ago.
* [Mozilla Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1731418) (created on  2021-09-18)
* [URLPattern WPT Tests](https://wpt.fyi/results/urlpattern?label=experimental&label=master&aligned)

**Comment by wanderview** [comment]
FYI, we are making a small enhancement to URLPattern to add the option to perform case-insensitive matching.  This was a web developer community request.  Please see:

https://groups.google.com/a/chromium.org/g/blink-dev/c/hNUoDg94-_8/m/-Cnv2qyMAAAJ
https://github.com/WICG/urlpattern/issues/148

Note, since this is a small change I thought it might be better to comment here instead of creating a new issue.  If you would prefer a new issue, please let me know.

**Comment by annevk** [comment]
Thanks @wanderview, that seems fine. If you have the time, what is the latest on getting this more formally standardized as well as fixing some of the remaining issues?

**Comment by wanderview** [comment]
If you mean moving urlpattern into whatwg, that is still something I would like to do but is a lower priority at the moment.  If another browser indicates they want to start implementing it would raise the priority of doing that work.

**Comment by annevk** [comment]
I'm going to mark this as blocked. We'd be supportive of this if it was maintained and the venue issue was resolved. Additionally if-and-when we should carefully look at the CSP use cases around matching and ensure there's parity.

**Comment by annevk** [comment]
After having discussed this at the most recent W3C TPAC, the maintenance issue and venue question have been resolved. As mentioned above I suggest we mark this as "position: support" one week from now therefore.
