### ISSUE TITLE
Screen Wake Lock API

### ISSUE THREAD

**Issue by marcoscaceres** [WebKit/standards-positions#63]
## Request for position on an emerging web specification

* WebKittens who can provide input: @marcoscaceres 

### Information about the spec

* Spec Title: Screen Wake Lock API
* Spec URL: https://www.w3.org/TR/screen-wake-lock/
* GitHub repository: https://github.com/w3c/screen-wake-lock/
* Issue Tracker (if not the repository's issue tracker): 
* Explainer (if not README.md in the repository): https://github.com/w3c/screen-wake-lock/blob/gh-pages/explainer.md

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/126
* Mozilla standards-positions issue: https://mozilla.github.io/standards-positions/#screen-wake-lock. 

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=205104
* Radar: rdar://71618179

### Anything else we need to know

An API that allows web applications to request a screen wake lock. Under the right conditions, and if allowed, the screen wake lock prevents the system from turning off a device's screen.

cc @kenchris @beaufortfrancois @rakuco

**Comment by tomayac** [comment]
I can’t edit your description, but the WebKit bug is https://bugs.webkit.org/show_bug.cgi?id=205104.

**Comment by marcoscaceres** [comment]
Draft postion: 

> We are supportive of the Screen Wake Lock API and have an [implementation in WebKit](https://github.com/WebKit/WebKit/tree/main/Source/WebCore/Modules/screen-wake-lock). However, we remain concerned about adverse impacts on users’ battery life and hope that through real-world usage experience we can mitigate these concerns. 

Unless anyone objects by Friday 14th of October, we will make the above the "official position".

**Comment by marcoscaceres** [comment]
As the CFC has passed, labelling with position: support.

**Comment by pelord** [comment]
Do you know if there is a target iOS version for the release of this new feature?

**Comment by marcoscaceres** [comment]
No, sorry. I don’t know.

**Comment by hober** [comment]
Closing as we've identified our position.
