### ISSUE TITLE
Opaque Response Blocking (ORB, aka CORB++)

### ISSUE THREAD

**Issue by sysrqb** [WebKit/standards-positions#64]
### Information about the spec

* Spec Title: Opaque Response Blocking (ORB, aka CORB++)
* Spec URL: https://whatpr.org/fetch/1442.html
* GitHub repository: https://github.com/annevk/orb

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/860

Mozilla is implementing: https://bugzilla.mozilla.org/show_bug.cgi?id=1532642.

### Anything else we need to know

https://lists.webkit.org/pipermail/webkit-dev/2022-May/032222.html

**Comment by annevk** [comment]
Colleagues and I discussed this (though quite a while ago now, my bad) and think this is worth pursuing as it provides defense-in-depth for a significant number of subresources. In particular this proposal helps guard:

- same-site-but-cross-origin subresources (these always get cookies)
- cross-origin subresources when Storage Access is active for their origin
- cross-origin subresources on local networks

As such I suggest we mark this "position: support" one week from now.
