### ISSUE TITLE
Deprecating Non-ASCII characters in cookie domain attributes

### ISSUE THREAD

**Issue by marcoscaceres** [WebKit/standards-positions#7]
## Request for position on an emerging web specification

**(Please delete inapplicable rows.)**

* WebKittens who can provide input: @johnwilander

### Information about the spec

* Spec Title: 
* Spec URL: 
* GitHub repository: 
* Issue Tracker (if not the repository's issue tracker): 
* Explainer (if not README.md in the repository): 

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: 

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

On [webkit-dev](https://lists.webkit.org/pipermail/webkit-dev/2022-June/032306.html), @johannhof wrote: 

Hi folks,

This is a heads up that I'm planning to deprecate non-ASCII characters in
cookie domain attributes in Chromium, meaning that these cookies will be
rejected going forward. See
https://groups.google.com/a/chromium.org/g/blink-dev/c/x3DY-PuZhNw for all
details.

This is following a discussion in the [HTTP WG](https://github.com/httpwg/http-extensions/issues/1707) and subsequent
[specification](https://github.com/httpwg/http-extensions/pull/1969) in RFC 6265bis. While John Wilander from Apple was part of the discussion, I'd still like to extend the request to this list to give feedback on the proposal.

>From my understanding, for Safari, this is handled in the OS network stack
instead of WebKit, and I believe the internal bug on your side to
be rdar://88349235

As both Chromium and Safari currently accept these cookies, there is a
potential for breakage. However, in Chrome, usage appears to be low enough
to move forward with deprecation and removal, see the linked thread above.

Thanks!

Johann

**Comment by hober** [comment]
cc @achristensen07

**Comment by annevk** [comment]
Apologies for the late follow-up, but this is something we're supportive of. I suggest we add a label 7 days from now.

**Comment by hober** [comment]
Closing as we've identified our position.
