### ISSUE TITLE
CSS lh and rlh units

### ISSUE THREAD

**Issue by lilles** [WebKit/standards-positions#75]
### Information about the spec

* Spec Title: CSS Values and Units Module Level 4
* Spec URL: https://www.w3.org/TR/css-values-4/#lh
* GitHub repository: https://github.com/w3c/csswg-drafts

### Design reviews and vendor positions

* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/699

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=195180

### Anything else we need to know

Blink plan to ship lh first (without rlh, just practical reasons), but asking for position on both.

**Comment by gsnedders** [comment]
I'm just gonna go ahead and label this with "support" given we've already implemented it, and it got enabled by default (both `lh` and `rlh`) in https://bugs.webkit.org/show_bug.cgi?id=246522 (https://github.com/WebKit/WebKit/pull/5377).

cc @nt1m

**Comment by annevk** [comment]
(While that's probably fine in this case, we might implement something we're opposed to as a project. E.g., because we need to do it for compatibility reasons. As such our position doesn't always follow from implementation status.)

**Comment by hober** [comment]
Closing as we've identified our position.
