### ISSUE TITLE
ECMAScript Decorators

### ISSUE THREAD

**Issue by bennypowers** [WebKit/standards-positions#76]
## Request for position on an emerging web specification

* WebKittens who can provide input: 

### Information about the spec

* Spec Title: Decorators
* Spec URL: https://github.com/tc39/proposal-decorators
* GitHub repository: https://github.com/tc39/proposal-decorators

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: https://mozilla.github.io/standards-positions/#tc39-stage-3

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

ECMAScript decorators have reached stage 3, [TypeScript is working on implementing the new stage-3 version](https://github.com/microsoft/TypeScript/pull/50820/files#). What is Webkit's position on the spec and when would they consider prototyping?

**Comment by Constellation** [comment]
Hello! This is TC39 stage-3, it means that we already agreed to prototype this proposal at TC39.
You can check stage-3 criteria for details. https://tc39.es/process-document/

**Comment by bennypowers** [comment]
Great! Thanks.

**Comment by woody-li** [comment]
Is there any implement task?
I don't find it on Bugzilla.

**Comment by trusktr** [comment]
Where can we see implementation status?

**Comment by trusktr** [comment]
I couldn't find the bugzilla tracking ticket, so I opened one at https://bugs.webkit.org/show_bug.cgi?id=277593

**Comment by trusktr** [comment]
The other implementations are tracked here, for convenience:

- Firefox:
  - Meta issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1435869
  - Implementation issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1781212
- Chromium/Edge:
  - Implementation issue: https://issues.chromium.org/issues/42202709
  - List of changesets in review: https://chromium-review.googlesource.com/q/hashtag:%22decorators%22
