### ISSUE TITLE
Improving event dispatching on disabled form controls

### ISSUE THREAD

**Issue by josepharhar** [WebKit/standards-positions#78]
## Request for position on an emerging web specification

* WebKittens who can provide input: @rniwa and @annevk who have commented on https://github.com/whatwg/html/issues/2368 and https://github.com/whatwg/html/issues/5886

### Information about the spec

The portion of the HTML spec about this is quite terse and will likely be rewritten based on the consensus that comes out of these spec issues:
- https://github.com/whatwg/html/issues/2368
- https://github.com/whatwg/html/issues/5886

### Design reviews and vendor positions

* TAG Design Review: none
* Mozilla standards-positions issue: none, but I believe that mozilla is supportive

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know

Supporting this in WebKit as the change is currently proposed would require these changes:
1. Allow mouse and pointer events to be fired on disabled form controls, except `mouseup`, `mousedown`, and `click`
2. Allow `mouseup`, `mousedown`, and `click` to be fired on child elements of disabled form controls when they are clicked, which can be achieved by truncating the event path. This is what firefox currently does.

I filed this in response to feedback in my [intent to ship for chrome](https://groups.google.com/a/chromium.org/g/blink-dev/c/9i0H0J0BzE4), where I am going to try to launch this behavior and hope that it doesn't break too many websites.

**Comment by bennypowers** [comment]
Seems this might be related to https://bugzilla.mozilla.org/show_bug.cgi?id=1800370

**Comment by karlcow** [comment]
So this is part of interop-2023 effort
https://wpt.fyi/results/html/semantics/disabled-elements/disabled-event-dispatch.tentative.html?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-webcompat

**Comment by karlcow** [comment]
Opened https://bugs.webkit.org/show_bug.cgi?id=251246

**Comment by annevk** [comment]
Given that WebKit is participating in Interop 2023 let's resolve this as "position: support" in 7 days.

**Comment by hober** [comment]
Closing as we've identified our position.
