### ISSUE TITLE
`modulepreload` links

### ISSUE THREAD

**Issue by bennypowers** [WebKit/standards-positions#81]
## Request for position on an emerging web specification

* WebKittens who can provide input: 

### Information about the spec

* Spec Title: Link Type "modulepreload"
* Spec URL: https://html.spec.whatwg.org/multipage/links.html#link-type-modulepreload
* Explainer (if not README.md in the repository): https://developer.chrome.com/blog/modulepreload/

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/213
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/635

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=180574
* Radar: rdar://problem/88670991

### Anything else we need to know

Allows page authors to hint to the browser to preload es modules into the module graph. This can resolve waterfall performance issues with deep module graphs.

**Comment by annevk** [comment]
Colleagues and I looked at this and are supportive. As such I suggest we label this with "position: support" in 7 days.

**Comment by hober** [comment]
Closing as we've identified our position.
