### ISSUE TITLE
Priority Hints

### ISSUE THREAD

**Issue by annevk** [WebKit/standards-positions#87]
## Request for position on an emerging web specification

* WebKittens who can provide input: @youennf 

### Information about the spec

* Spec URL: https://wicg.github.io/priority-hints/
   * https://github.com/whatwg/fetch/pull/1523
   * https://github.com/whatwg/html/pull/8470
* GitHub repository: https://github.com/WICG/priority-hints
* Explainer (if not README.md in the repository): https://github.com/WICG/priority-hints/blob/main/EXPLAINER.md

### Design reviews and vendor positions

* TAG Design Review: https://github.com/w3ctag/design-reviews/issues/704
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/606

### Bugs tracking this feature

* WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=247291
* Radar: rdar://problem/102058327

### Anything else we need to know

Previously requested at https://lists.webkit.org/pipermail/webkit-dev/2022-January/032087.html.

The idea is essentially giving a high-level hint to the network layer about the importance of a request (and also expose this to service workers).

**Comment by youennf** [comment]
This looks ok to me.
Network libraries have some support and WebKit has this notion of priority as well.
The use case of a website stating that some image loads are lower priority than others makes sense to me.

**Comment by annevk** [comment]
I suggest we label this as "position: support" one week from now.

**Comment by hober** [comment]
Closing as we've identified our position.
