### ISSUE TITLE
Auto-sizes for lazy-loaded images in HTML

### ISSUE THREAD

**Issue by marcoscaceres** [WebKit/standards-positions#9]
## Request for position on an emerging web specification

**(Please delete inapplicable rows.)**

* WebKittens who can provide input: 

### Information about the spec

* Spec Title: Add sizes=auto to lazy-loaded `<img>`
* Spec URL: https://github.com/whatwg/html/pull/8008
* GitHub repository: 
* Issue Tracker (if not the repository's issue tracker): https://github.com/whatwg/html/issues/4654
* Explainer (if not README.md in the repository): 

### Design reviews and vendor positions

* TAG Design Review: 
* Mozilla standards-positions issue: https://github.com/mozilla/standards-positions/issues/650

### Bugs tracking this feature

* WebKit Bugzilla: 
* Radar: 

### Anything else we need to know
On [webkit-dev](https://lists.webkit.org/pipermail/webkit-dev/2022-June/032301.html), @zcorpan wrote: 

I'd like WebKit's position on the proposal: Add sizes=auto to lazy-loaded `<img>`

This allows web developers to omit the `sizes` attribute, or explicitly specify `sizes=auto`, for `<img>` elements that have `loading=lazy`. The browser will use the layout width of the image as input to the srcset resource selection (lazy images don't start loading until layout is known, at the earliest). For eager-loading images, it's invalid and equivalent to `100vw`.

Chromium position:
https://github.com/whatwg/html/issues/4654#issuecomment-1154412434

**Comment by hober** [comment]
@smfr @rniwa @litherum @jensimmons, thoughts?

**Comment by annevk** [comment]
Colleagues and I think this is a reasonable addition. I suggest we mark this as "position: support" in seven days.

**Comment by hober** [comment]
Closing as we've identified our position.

**Comment by styfle** [comment]
WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=253143
