### ISSUE TITLE
PWAs should be able to use all browser API

### ISSUE THREAD

**Issue by jogibear9988** [WebKit/standards-positions#99]
## Request for position on an emerging web specification

The other Browser allow all API access also in PWA Mode, but Safari has restrictions. For example in IOS you could not use RTC video Stream in PWA Mode (https://github.com/webrtc/samples/issues/933). Maybe more such issues exist.

* WebKittens who can provide input: 

### Information about the spec

* Spec Title: Didn't find really a spec but many descriptions
* Spec URL: https://web.dev/learn/pwa/capabilities/
* GitHub repository: 
* Issue Tracker (if not the repository's issue tracker): 
* Explainer (if not README.md in the repository):

**Comment by annevk** [comment]
In principle there ought to not be any difference between Safari and installed web applications. If you find such differences please do report them on http://bugs.webkit.org/ or http://feedbackassistant.apple.com/ so they can be addressed.

As this GitHub repository is for determining the position of the WebKit project on web standards, I'll close this issue, but please do comment if there is something unclear.
